### ISSUE TITLE
NoneType object has no attribute config_get

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/ays9#10]
#### Installation information

- jumpscale version: 9
- operating system: ubuntu 17.04

#### Detailed description
When starting ays `ays start`
```
/opt/code/github/jumpscale/ays9/examples/docker_ovc/: 'NoneType' object has no attribute 'config_get'
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/JobController.py", line 33, in __init__
    RunsCollection(),
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/models/RunsCollection.py", line 20, in __init__
    db = j.data.kvs.getRedisStore(namespace, namespace, **j.atyourservice.server.config['redis'])
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 189, in config
    cfg.update({'redis': j.core.db.config_get('unixsocket')})
AttributeError: 'NoneType' object has no attribute 'config_get'
```
#### Steps to reproduce
Execute `ays start`

#### Relevant stacktraces

```
2017-05-29 12:00:17 - (sanic)[INFO]: Goin' Fast @ http://127.0.0.1:5000
[Mon29 12:00] - TemplateRepo.py     :53  :j.atyourservice.server         - INFO     - reload actor templates repos
[Mon29 12:00] - TemplateRepo.py     :260 :j.atyourservice.server         - INFO     - reload actor templates from /opt/code/github/jumpscale/ays9/
[Mon29 12:00] - TemplateRepo.py     :260 :j.atyourservice.server         - INFO     - reload actor templates from /opt/code/github/jumpscale/ays9
[Mon29 12:00] - AtYourServiceRepo.py:31  :j.atyourservice.server         - INFO     - reload AYS repos
[Mon29 12:00] - AtYourServiceRepo.py:41  :j.atyourservice.server         - ERROR    - can't load repo at /opt/code/github/jumpscale/ays9/examples/docker_ovc/: 'NoneType' object has no attribute 'config_get'
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 38, in _load
    repo = AtYourServiceRepo(path, loop=self._loop)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 174, in __init__
    j.atyourservice.server._loadActionBase()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 344, in _loadActionBase
    action_code_model = j.core.jobcontroller.getActionObjFromMethod(method)
  File "/usr/lib/python3/dist-packages/js9.py", line 1762, in jobcontroller
    self._jobcontroller = JobController()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/JobController.py", line 33, in __init__
    RunsCollection(),
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/models/RunsCollection.py", line 20, in __init__
    db = j.data.kvs.getRedisStore(namespace, namespace, **j.atyourservice.server.config['redis'])
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 189, in config
    cfg.update({'redis': j.core.db.config_get('unixsocket')})
AttributeError: 'NoneType' object has no attribute 'config_get'
[Mon29 12:00] - AtYourServiceRepo.py:41  :j.atyourservice.server         - ERROR    - can't load repo at /opt/code/github/jumpscale/ays9/examples/kvm_packet.net/: 'NoneType' object has no attribute 'config_get'
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 38, in _load
    repo = AtYourServiceRepo(path, loop=self._loop)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 174, in __init__
    j.atyourservice.server._loadActionBase()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 344, in _loadActionBase
    action_code_model = j.core.jobcontroller.getActionObjFromMethod(method)
  File "/usr/lib/python3/dist-packages/js9.py", line 1762, in jobcontroller
    self._jobcontroller = JobController()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/JobController.py", line 33, in __init__
    RunsCollection(),
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/models/RunsCollection.py", line 20, in __init__
    db = j.data.kvs.getRedisStore(namespace, namespace, **j.atyourservice.server.config['redis'])
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 189, in config
    cfg.update({'redis': j.core.db.config_get('unixsocket')})
AttributeError: 'NoneType' object has no attribute 'config_get'
[Mon29 12:00] - RunScheduler.py     :70  :j.ays.runscheduler             - INFO     - RunScheduler<docker_ovc> started
[Mon29 12:00] - RunScheduler.py     :70  :j.ays.runscheduler             - INFO     - RunScheduler<kvm_p
```

**Comment by ashraffouda** [comment]
Can u check again if this issue is fixed or not? supposed u have an old code
