### ISSUE TITLE
AYS can't load newly created repo

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/ays9#12]
#### Installation information

- jumpscale version:9
- operating system:17.04

#### Detailed description
When creating a new AYS repo it produces the following error:
`can't load repo at /optvar/cockpit_repos/ali: ERROR: could not find basepath for .git in ((type:runtime.error)                                `

#### Steps to reproduce
Run following command `ays repo create -g {git url} -n {name}`

#### Relevant stacktraces
```
Traceback (most recent call last):                                                                                 │       ,lcc'.........,;...,;.    ................',c:,''........,.  .o   .;;xccccccccld:
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 57, in handle_fs_events  │        .';ccc:;;,,'.  ...  ..''..             ;;'...............';.c'.''.  ;loolloooo;
    repo = AtYourServiceRepo(current_path, loop=self._loop)                                                        │                                ..',,,,,,,''...:o,.................c           ....
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 160, in __init__         │                                               .;l.................c.
    self.git = j.clients.git.get(self.path, check_path=False)                                                      │                                                 ;;;;,'..........,;,
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitFactory.py", line 144, in get                   │                                                    .':ldddoooddl'
    return GitClient(basedir, check_path=check_path)                                                               │gig:js9:/optvar/cockpit_repos/first$vim /opt/code/github/
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitClient.py", line 28, in __init__                │jumpscale/core9/JumpScale9/clients/git/GitClient.py
    raise j.exceptions.RuntimeError("could not find basepath for .git in %s" % baseDir)                            │gig:js9:/optvar/cockpit_repos/first$ls ..
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: could not find basepath for .git in  ((type:runtime.erro│d  first
r)                                 
```

**Comment by alichaddad** [comment]
Should be fixed after https://github.com/Jumpscale/ays9/commit/f00ebe4baae6ccb2aba023a70e50f0e430dde679
