### ISSUE TITLE
Error: Repository orchestrator-server doesn't exists 

### ISSUE THREAD

**Issue by jvwilder** [Jumpscale/ays9#129]
#### Installation information

- jumpscale version: master
- operating system: Ubuntu 16.04

#### Detailed description
When trying to do 'ays repo destroy' to do a reset, it gives the error 'Error while destroying repository: Repository orchestrator-server doesn't exists'. Suddenly the orchestrator-server repo is gone and a reinstall is needed to get it fixed.

#### Relevant stacktraces
When trying to restart ays:
 ``` 
ERROR - can't load repo at /optvar/cockpit_repos/orchestrator-server/: ERROR: error:Expected object or value
\could not parse: 
path:/optvar/cockpit_repos/orchestrator-server/services/configuration!main/data.json
 ((type:input.error)
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/core9/JumpScale9/data/serializers/SerializerBase.py", line 13, in load
    r = self.loads(b)
  File "/opt/code/github/jumpscale/core9/JumpScale9/data/serializers/SerializerUJson.py", line 16, in loads
    return json.loads(s)
ValueError: Expected object or value

```

**Comment by rkhamis** [comment]
There seems to be an error in the service data of "configuration!main"

This will cause this repo to be unloadable in the Ays server. Did you
manually change anything?

On Jul 27, 2017 16:18, "jvwilder" <notifications@github.com> wrote:

Installation information

   - jumpscale version: master
   - operating system: Ubuntu 16.04

Detailed description

When trying to do 'ays repo destroy' to do a reset, it gives the error
'Error while destroying repository: Repository orchestrator-server doesn't
exists'. Suddenly the orchestrator-server repo is gone and a reinstall is
needed to get it fixed.
Steps to reproduce Relevant stacktraces

When trying to restart ays:

ERROR - can't load repo at /optvar/cockpit_repos/orchestrator-server/:
ERROR: error:Expected object or value
\could not parse:
path:/optvar/cockpit_repos/orchestrator-server/services/configuration!main/data.json
((type:input.error)
Traceback (most recent call last):
 File "/opt/code/github/jumpscale/core9/JumpScale9/data/serializers/SerializerBase.py",
line 13, in load
   r = self.loads(b)
 File "/opt/code/github/jumpscale/core9/JumpScale9/data/serializers/SerializerUJson.py",
line 16, in loads
   return json.loads(s)
ValueError: Expected object or value


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jumpscale/ays9/issues/129>, or mute the thread

**Comment by jvwilder** [comment]
I did not change anything, but the 'data.json' file was empty when I checked.
