### ISSUE TITLE
Core dump during deployment of a storage cluster

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/ays9#15]
#### Installation information

- jumpscale version: 9.0.0
- operating system: Linux

#### Detailed description
AYS core dumped during deployment of a zero-os storage cluster (https://github.com/zero-os/0-orchestrator/tree/master/templates/storage_cluster)

#### Steps to reproduce
- Install js9 docker
- install orchestrator (https://github.com/zero-os/0-orchestrator/blob/master/scripts/install-orchestrator.sh)
- try to deploy a storage cluster

**Comment by FastGeert** [comment]
New core dump while creating vdisk

```
[Wed07 07:19] - Job.py              :56  :j.core.jobcontroller.job.38d948b0c9224864148f7d1301076538 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/f736efe557c87057827b8c85dc2e5147.py", line 28, in install
    targetconfig = get_storagecluster_config(service)
  File "/tmp/actions/vdisk/f736efe557c87057827b8c85dc2e5147.py", line 181, in get_storagecluster_config
    cluster = StorageCluster.from_ays(storageclusterservice)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 32, in from_ays
    storages_server = StorageServer.from_ays(ardb_service)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 147, in from_ays
    ardb = ARDB.from_ays(ardb_services)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/ARDB.py", line 29, in from_ays
    container = Container.from_ays(service.parent)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 86, in from_ays
    for portmap in service.model.data.ports:
  File "capnp/lib/capnp.pyx", line 1263, in capnp.lib.capnp._DynamicStructBuilder.__getattr__ (capnp/lib/capnp.cpp:26887)
  File "capnp/lib/capnp.pyx", line 1261, in capnp.lib.capnp._DynamicStructBuilder.__getattr__ (capnp/lib/capnp.cpp:26802)
  File "capnp/lib/capnp.pyx", line 1254, in capnp.lib.capnp._DynamicStructBuilder._get (capnp/lib/capnp.cpp:26507)
capnp.lib.capnp.KjException: src/capnp/layout.c++:1844: failed: expected ref->kind() == WirePointer::STRUCT; Message contains
 non-struct pointer where struct pointer was expected.
stack: 0x7ffa99934639 0x7ffa9993826d 0x7ffa998e315c 0x7ffa998dbfd3 0x7ffa998e8e96 0x7ffa998e90f9 0x7ffa998e9426 0x7ffa998ea495 0x7ffa99906304 0x7ffa997f2138 0x7ffa997a479c 0x52424b 0x528814 0x528814 0x528814 0x528814
[Wed07 07:19] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Wed07 07:19] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run a85ac1acd76cde8f2c1b6cd00a4fe143
Error of job: vdisk!vdisk-1 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/f736efe557c87057827b8c85dc2e5147.py", line 28, in install
    targetconfig = get_storagecluster_config(service)
  File "/tmp/actions/vdisk/f736efe557c87057827b8c85dc2e5147.py", line 181, in get_storagecluster_config
    cluster = StorageCluster.from_ays(storageclusterservice)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 32, in from_ays
    storages_server = StorageServer.from_ays(ardb_service)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 147, in from_ays
    ardb = ARDB.from_ays(ardb_services)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/ARDB.py", line 29, in from_ays
    container = Container.from_ays(service.parent)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 86, in from_ays
    for portmap in service.model.data.ports:
  File "capnp/lib/capnp.pyx", line 1263, in capnp.lib.capnp._DynamicStructBuilder.__getattr__ (capnp/lib/capnp.cpp:26887)
  File "capnp/lib/capnp.pyx", line 1261, in capnp.lib.capnp._DynamicStructBuilder.__getattr__ (capnp/lib/capnp.cpp:26802)
  File "capnp/lib/capnp.pyx", line 1254, in capnp.lib.capnp._DynamicStructBuilder._get (capnp/lib/capnp.cpp:26507)
capnp.lib.capnp.KjException: src/capnp/layout.c++:1844: failed: expected ref->kind() == WirePointer::STRUCT; Message contains
 non-struct pointer where struct pointer was expected.
stack: 0x7ffa99934639 0x7ffa9993826d 0x7ffa998e315c 0x7ffa998dbfd3 0x7ffa998e8e96 0x7ffa998e90f9 0x7ffa998e9426 0x7ffa998ea49
5 0x7ffa99906304 0x7ffa997f2138 0x7ffa997a479c 0x52424b 0x528814 0x528814 0x528814 0x528814


******************************************************************************************

```

**Comment by xmonader** [comment]
Fixed by this https://github.com/Jumpscale/ays9/pull/20
