### ISSUE TITLE
Error sometimes when restart ays 

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/ays9#164]
#### Error
```
uture: <Future finished exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x256bc48>; the handler is closed',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 568, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 632, in _process_write_backlog
    self._transport.write(chunk)
  File "uvloop/handles/stream.pyx", line 632, in uvloop.loop.UVStream.write (uvloop/loop.c:74612)
  File "uvloop/handles/handle.pyx", line 150, in uvloop.loop.UVHandle._ensure_alive (uvloop/loop.c:54917)
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x256bc48>; the handler is closed
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x256bc48>; the handler is closed',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 568, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 632, in _process_write_backlog
    self._transport.write(chunk)
  File "uvloop/handles/stream.pyx", line 632, in uvloop.loop.UVStream.write (uvloop/loop.c:74612)
  File "uvloop/handles/handle.pyx", line 150, in uvloop.loop.UVHandle._ensure_alive (uvloop/loop.c:54917)
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x256bc48>; the handler is closed
[Wed09 14:24] - server.py           :509 :asyncio                        - ERROR    - Exception in callback UVTransport._start_reading
handle: <Handle UVTransport._start_reading>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 52, in uvloop.loop.Handle._run (uvloop/loop.c:48414)
  File "uvloop/handles/stream.pyx", line 257, in uvloop.loop.UVStream._start_reading (uvloop/loop.c:70782)
  File "uvloop/handles/handle.pyx", line 150, in uvloop.loop.UVHandle._ensure_alive (uvloop/loop.c:54917)
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x256bc48>; the handler is closed
ERROR:asyncio:Exception in callback UVTransport._start_reading
handle: <Handle UVTransport._start_reading>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 52, in uvloop.loop.Handle._run (uvloop/loop.c:48414)
  File "uvloop/handles/stream.pyx", line 257, in uvloop.loop.UVStream._start_reading (uvloop/loop.c:70782)
  File "uvloop/handles/handle.pyx", line 150, in uvloop.loop.UVHandle._ensure_alive (uvloop/loop.c:54917)
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x256bc48>; the handler is closed
2017-08-09 14:24:18 - (sanic)[INFO]: Starting worker [29083]
```

## Software version
c08b65c5d6edff81b79a020f8ec7b02eb3f59d5a

**Comment by Dinaamagdy** [comment]
```[Mon18 13:25] - f08aaf530550dbd9dd9bb1b3c14ce32f.py:238 :j.core.jobcontroller.job.afbe39782715f07a701fc4b59a8d1deb 
- ERROR    - 
[Mon18 13:25] - b6264be0b498bd61a44975195682b5db.py:238 :j.core.jobcontroller.job.c0bcb0f8c6e142b04c7f2ef2ab2a5c7c 
- ERROR    - 
^C[Mon18 13:26] - 5fe794f16528bab057497aa48bff1451.py:238 :j.core.jobcontroller.job.1c8e86bb9bcded345ebde80eaeb2649
2 - ERROR    - 
```



```
RuntimeError: Member was null.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 625, in _process_write_backlog
    self._on_handshake_complete)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 128, in do_handshake
    raise RuntimeError('handshake in progress or completed')
RuntimeError: handshake in progress or completed
ERROR:asyncio:Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f0437962400>
transport: <TCPTransport closed=True reading=False 0x33b5d98>
Traceback (most recent call last):
  File "capnp/lib/capnp.pyx", line 1354, in capnp.lib.capnp._DynamicStructBuilder._which (capnp/lib/capnp.cpp:28794
)
RuntimeError: Member was null.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 625, in _process_write_backlog
    self._on_handshake_complete)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 128, in do_handshake
    raise RuntimeError('handshake in progress or completed')
RuntimeError: handshake in progress or completed
```

**Comment by hossamabdullah** [comment]
can not reproduce
