### ISSUE TITLE
ays produce cant find service with key error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [Jumpscale/ays9#167]
#### Installation information

- jumpscale version: 9.1.1
- operating system: ubuntu 16

#### Detailed description

i executed the bootstap, network , config, etcd, and statistics blueprints 
after a while i destroyed the repo and restart all the nodes then i executed the bootstrap and the etcd bps after that i created storagecluster

##### ays error
```
[Thu10 11:16] - Job.py              :56  :j.core.jobcontroller.job.3f280539647e8b2bcd8dac91f100c53a - ERROR    - Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 338, in serviceGet
    return self.db.services.services[key]
KeyError: '3f68d19eb21aa617041dc18aa2a17405'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.zero-os/43cb081f156ae67e37ead4a2311158d9.py", line 382, in monitor
    stats_collector_service = get_stats_collector(service)
  File "/tmp/actions/node.zero-os/43cb081f156ae67e37ead4a2311158d9.py", line 176, in get_stats_collector
    stats_collectors_services = service.consumers.get('stats_collector')
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 447, in consumers
    consumers[role].append(self.aysrepo.serviceGet(key=cons.key))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 340, in serviceGet
    raise j.exceptions.NotFound('cant find service with key %s' % key)
JumpScale9.errorhandling.JSExceptions.NotFound: ERROR: cant find service with key 3f68d19eb21aa617041dc18aa2a17405 ((type:notfound)
```

**Comment by rkhamis** [comment]
I think this issue has been fixed since https://github.com/Jumpscale/ays9/pull/147

**Comment by john-kheir** [comment]
This issue doesn't happen now
