### ISSUE TITLE
Error in watch_repos

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/ays9#17]
#### Installation information

- jumpscale version: 9.0
- operating system: Linux

#### Detailed description
The error shown in the stack trace occurs when starting AYS server

#### Steps to reproduce
start ays server

#### Relevant stacktraces
```
Traceback (most recent call last):                                                                 │- ardb                      cluster_0cc47a3aad5a_bigmomma_sdf_data_26 | install         (ok)
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner                            │- ardb                      cluster_0cc47aab6702_bigmomma_sdb_data_29 | install         (ok)
    self.run()                                                                                     │- ardb                      cluster_0cc47aab670a_bigmomma_sdc_data_37 | install         (ok)
  File "/usr/lib/python3.5/threading.py", line 862, in run                                         │- ardb                      cluster_0cc47aab6444_bigmomma_sdb_data_57 | install         (ok)
    self._target(*self._args, **self._kwargs)                                                      │- ardb                      cluster_0cc47a3b3d6a_bigmomma_sde_data_46 | install         (ok)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 141, in _w│- ardb                      cluster_0cc47a3b3d98_bigmomma_sdg_data_20 | install         (ok)
atch_repos                                                                                         │- ardb                      cluster_0cc47aab6702_bigmomma_sde_data_32 | install         (ok)
    i = AYSNotify([d.encode() for d in [j.dirs.VARDIR, j.dirs.CODEDIR]], mask=mask)                │- ardb                      cluster_0cc47a3b3d98_bigmomma_sdd_data_17 | install         (ok)
  File "/usr/local/lib/python3.5/dist-packages/inotify/adapters.py", line 261, in __init__         │- ardb                      cluster_0cc47aab6702_bigmomma_sdf_data_33 | install         (ok)
    self.__load_trees(paths)                                                                       │- ardb                      cluster_0cc47aab66e2_bigmomma_sda_data_49 | install         (ok)
  File "/usr/local/lib/python3.5/dist-packages/inotify/adapters.py", line 264, in __load_trees     │- ardb                      cluster_0cc47aab6702_bigmomma_sdc_data_30 | install         (ok)
    _LOGGER.debug("Adding initial watches on trees: [%s]", ",".join(paths))                        │step:5 (ok)
TypeError: sequence item 0: expected str instance, bytes found  
```

**Comment by arahmanhamdy** [comment]
@zaibon seems that you have installed the inotify library from other source than our gigforks (which is installed with ays9 by default). Please try to install it from: https://github.com/gigforks/PyInotify

**Comment by zaibon** [comment]
The js9 installer need to be updated then cause I use https://github.com/Jumpscale/developer to install

**Comment by arahmanhamdy** [comment]
@zaibon The js9 installer already uses this fork when you build the container normally:
https://github.com/Jumpscale/ays9/blob/master/setup.py#L17

**Comment by zaibon** [comment]
Why is this installed like that in the first place ? This line should part of the `install_requires`  in the setup function.  

but other then that, if we indeed install the correct version, then it's indeed a bug

**Comment by zaibon** [comment]
I just tested with the correct lib installed, error is gone.
So we need to validate the correct lib if installed

**Comment by arahmanhamdy** [comment]
I didn't get the reason for using `pip3 install ` instead of adding it to `install_requires`
https://github.com/Jumpscale/ays9/commit/ac8dfcb6db734a008402c289764ff42d6d2946e6

I have tested normal installation and it installed and worked with the correct version
