### ISSUE TITLE
Unexpected error when creating a new user with uservdc service

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#209]
#### Installation information

- jumpscale version: master
- operating system: JS9/Docker

#### Detailed description

When executing a run from the below blueprints, you get:
Usernames can only contain alphanumeric characters, dots, dashes, underscores and should be

#### Steps to reproduce

```yaml
g8client__myg8:
  url: 'be-gen-1.demo.greenitglobe.com'
  login: 'artiliumadmin'
  password: 'artilium12345'
  account: 'Arne'
```

```yaml
uservdc__arne:
  g8client: myg8
  email: arne.vanbalgoijen@4tx.be
  provider: itsyouonline'
  groups:
    - user
```

```yaml
actions:
   - action: install
````

#### Relevant stacktraces

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/uservdc/a434127e98ca6ce916533e73ca2e12b6.py", line 57, in install
    if not client.api.system.usermanager.userexists(name=username):
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 44, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Usernames can only contain alphanumeric characters, dots, dashes, underscores and should be between 2 and 40 characters
```

**Comment by yveskerwyn** [comment]
problem was in the blueprint:

```yaml
 provider: itsyouonline'
```
