### ISSUE TITLE
error when start ays on freshly started js9 docker

### ISSUE THREAD

**Issue by ahmedelsayed-93** [Jumpscale/ays9#21]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Detailed description
![image](https://user-images.githubusercontent.com/24386820/27009161-7a0e0e78-4e87-11e7-9c65-160799167c39.png)

```
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/code/github/jumpscale/ays9/cmds/ays", line 673, in <module>
    cli()
  File "/opt/code/github/jumpscale/ays9/cmds/ays", line 590, in start
    j.atyourservice.server.start(bind=bind, port=port, log=log)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 92, in start
    rc, out = j.tools.prefab.local.tmux.executeInScreen(sname, "ays", cmd, reset=True, wait=5)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabTmux.py", line 170, in executeInScreen
    raise j.exceptions.RuntimeError(out)  # TODO: *1 does not seem to stop
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: 
**START**
2017-06-11 07:18:36 - (sanic)[DEBUG]:
```

#### Steps to reproduce
- start new js9 docker by js9_start
- ssh to js9 container
- ```run ays start```

**Comment by ahmedelsayed-93** [comment]
### software version
b7954b3
