### ISSUE TITLE
RuntimeError: if container the hostdir needs to exists

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#220]
#### Installation information

- jumpscale version: master
- operating system: js9/Docker

#### Detailed description

After having pulled to most recent changes from the master branches of jumpscale repositories, restarting AYS server fails to start, see traceback.

#### Relevant stacktraces

````
**START**
####INITENV
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from js9 import j
  File "/usr/lib/python3/dist-packages/js9.py", line 2, in <module>
    from JumpScale9.core.JSBase import JSBase
  File "/opt/code/github/jumpscale/core9/JumpScale9/__init__.py", line 105, in <module>
    j.tools.executorLocal.initEnv()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 239, in initEnv
    T=self._getDirPathConfig()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 170, in _getDirPathConfig
    raise RuntimeError("if container the hostdir needs to exists (/host)")
RuntimeError: if container the hostdir needs to exists (/host)
**ERROR**
```

**Comment by rkhamis** [comment]
needs to be reinstalled. As mentioned.
