### ISSUE TITLE
Error when authorizing user to vm

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/ays9#221]
#### Installation information

- jumpscale version:master(05a7b85)
- operating system: Ubuntu

#### Detailed description
The first time authorization to newly created vm happens it fails. In the second retry form the scheduler it succeeds.

#### Steps to reproduce
Use a blueprint to create a new VM see:https://github.com/Jumpscale/ays9/blob/master/templates/nodes/node.ovc/readme.md

#### Relevant stacktraces
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/4c2f9028ddc45f814c1f850584f1391d.py", line 292, in install
    prefab = _check_ssh_authorization(service, machine)
  File "/tmp/actions/node.ovc/4c2f9028ddc45f814c1f850584f1391d.py", line 393, in _check_ssh_authorization
    prefab = _ssh_authorize(service, vm_info)
  File "/tmp/actions/node.ovc/4c2f9028ddc45f814c1f850584f1391d.py", line 207, in _ssh_authorize
    executor.prefab.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabSSH.py", line 133, in authorize
    d = self.prefab.user.check(user, need_passwd=False)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabUser.py", line 82, in check
    _, d, _ = self.prefab.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1108, in run
    cmd = self.replace(cmd)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 275, in replace
    args2 = self.getArgsDict()
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 305, in getArgsDict
    for key, var in self.dir_paths.items():
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 215, in dir_paths
    return self.executor.dir_paths
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 336, in dir_paths
    self.initEnv()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 309, in initEnv
    self.state.configUpdate(TT, False)  # will not overwrite
  File "/opt/code/github/jumpscale/core9/JumpScale9/core/State.py", line 172, in configUpdate
    self.configSave()
  File "/opt/code/github/jumpscale/core9/JumpScale9/core/State.py", line 187, in configSave
    self.executor.file_write(self.configPath, data)
File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 392, in file_write
    res = self.execute(cmd)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorSSH.py", line 237, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 282, in execute
    "Cannot execute (ssh):\n%s\noutput:\n%serrors:\n%s" % (cmd, out.getvalue(), err.getvalue()))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Cannot execute (ssh):
set -e

set -e
mkdir -p /etc
echo "W3JlZGlzXQphZGRyID0gImxvY2FsaG9zdCIKcG9ydCA9IDYzNzkKZW5hYmxlZCA9IGZhbHNlCgpbZW1haWxdCmZyb20gPSAiaW5mb0BpbmN1YmFpZC5jb20iCnNtdHBfcG9ydCA9IDQ0MwpzbXRwX3NlcnZlciA9ICIiCgpbZ3JpZF0KbmlkID0gMApnaWQgPSAwCgpbc3lzdGVtXQpyZWFkb25seSA9I
GZhbHNlCmNvbnRhaW5lciA9IGZhbHNlCmF1dG9waXAgPSBmYWxzZQpkZWJ1ZyA9IHRydWUKClttZV0KbG9naW5uYW1lID0gInNvbWVpZCIKZnVsbG5hbWUgPSAiVGhpcyBpcyBteSBmdWxsIG5hbWUsIG5lZWRzIHRvIGJlIHJlcGxhY2UiCgpbc3NoXQpTU0hLRVlOQU1FID0gInNvbWVuYW1lIgoKW2RpcnNd
ClRFTVBMQVRFRElSID0gIi9vcHQvdmFyL3RlbXBsYXRlcyIKVkFSRElSID0gIi9vcHQvdmFyIgpMSUJESVIgPSAiL29wdC9saWIvIgpUTVBESVIgPSAiL3RtcCIKQkFTRURJUiA9ICIvb3B0IgpCSU5ESVIgPSAiL29wdC9iaW4iCkNGR0RJUiA9ICIvb3B0L2NmZyIKSE9TVERJUiA9ICIvaG9tZS9jbG91ZHN
jYWxlcnMvanM5aG9zdC8iCkxPR0RJUiA9ICIvb3B0L3Zhci9sb2ciCkJBU0VESVJKUyA9ICIvb3B0L2p1bXBzY2FsZTkiCkNPREVESVIgPSAiL29wdC9jb2RlIgpKU0FQUFNESVIgPSAiL29wdC9qdW1wc2NhbGU5L2FwcCIKQlVJTERESVIgPSAiL29wdC92YXIvYnVpbGQiCkRBVEFESVIgPSAiL29wdC92YX
IvZGF0YSIKSE9TVENGR0RJUiA9ICIvaG9tZS9jbG91ZHNjYWxlcnMvanM5aG9zdC9jZmcvIgpIT01FRElSID0gIi9ob21lL2Nsb3Vkc2NhbGVycyIK" | openssl base64 -A -d > /etc/jumpscale9.toml

output:
errors:
bash: line 4: /etc/jumpscale9.toml: Permission denied
 ((type:runtime.error)

```

**Comment by alichaddad** [comment]
Another possible execption:
```File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/1c540255f396baec3a6a767b898b4213.py", line 794, in install
    prefab = _check_ssh_authorization(service, machine)
  File "/tmp/actions/node.ovc/1c540255f396baec3a6a767b898b4213.py", line 200, in _check_ssh_authorization
    prefab = _ssh_authorize(service, vm_info)
  File "/tmp/actions/node.ovc/1c540255f396baec3a6a767b898b4213.py", line 217, in _ssh_authorize
    executor.prefab.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabSSH.py", line 133, in authorize
    d = self.prefab.user.check(user, need_passwd=False)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabUser.py", line 82, in check
    _, d, _ = self.prefab.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1099, in run
    cmd = self.replace(cmd)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 275, in replace
    args2 = self.getArgsDict()
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 305, in getArgsDict
    for key, var in self.dir_paths.items():
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 215, in dir_paths
    return self.executor.dir_paths
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 336, in dir_paths
    self.initEnv()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 240, in initEnv
    T=self._getDirPathConfig()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 168, in _getDirPathConfig
    hostdirexists= self.exists("/host")
File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 130, in exists
    return self.cache.get("exists:%s"%path, check)
  File "/opt/code/github/jumpscale/core9/JumpScale9/data/cache/Cache.py", line 115, in get
    val = method(**kwargs)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 125, in check
    rc,_,_=self.execute('test -e %s'%path,die=False,showout=False)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorSSH.py", line 237, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 214, in execute
    ch = self.transport.open_session()
AttributeError: 'NoneType' object has no attribute 'open_session'
```

The following error gets triggered when accessing same node.ovc multiple times:
```
File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/7b1df1cf8d77d04a3f9696a922c647d9.py", line 263, in install
    prefab = _check_ssh_authorization(service, machine)
  File "/tmp/actions/node.ovc/7b1df1cf8d77d04a3f9696a922c647d9.py", line 475, in _check_ssh_authorization
    prefab = _ssh_authorize(service, vm_info)
  File "/tmp/actions/node.ovc/7b1df1cf8d77d04a3f9696a922c647d9.py", line 286, in _ssh_authorize
    executor.prefab.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabSSH.py", line 133, in authorize
    d = self.prefab.user.check(user, need_passwd=False)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabUser.py", line 82, in check
    _, d, _ = self.prefab.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1099, in run
    cmd = self.replace(cmd)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 275, in replace
    args2 = self.getArgsDict()
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 307, in getArgsDict
    args["HOSTNAME"] = self.hostname
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 588, in hostname
    return self.cache.get("hostname", get)
  File "/opt/code/github/jumpscale/core9/JumpScale9/data/cache/Cache.py", line 115, in get
    val = method(**kwargs)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 585, in get
    rc, out, err = self.run("cat %s" % hostfile, showout=False, replaceArgs=False)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1107, in run
    ppath = self.prefab.bash.profileDefault.pathProfile
File "/opt/code/github/jumpscale/core9/JumpScale9/tools/bash/BashFactory.py", line 284, in profileDefault
    self._profileDefault = self.profileGet(path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/bash/BashFactory.py", line 263, in profileGet
    self.executor.file_write(path, "")
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 392, in file_write
    res = self.execute(cmd)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorSSH.py", line 237, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 282, in execute
    "Cannot execute (ssh):\n%s\noutput:\n%serrors:\n%s" % (cmd, out.getvalue(), err.getvalue()))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Cannot execute (ssh):
set -e

set -e
mkdir -p /root
echo "" | openssl base64 -A -d > /root/.bash_profile

output:
errors:
bash: line 4: /root/.bash_profile: Permission denied
 ((type:runtime.error)
```

**Comment by john-kheir** [comment]
Verified
