### ISSUE TITLE
ays actor update should reload schema

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#230]
#### Installation information

- jumpscale version: master
- operating system: js9/Docker

#### Detailed description

When creating a new actor template, using the the below `schema.capnp` we got an error saying:
```
error during execution of the blueprint myvdc.yaml: ERROR: Service template actor1 not found. Can't execute this blueprint ((type:input.error)
```

And also:
```
[Thu07 16:08] - AtYourServiceRepo.py:493 :j.atyourservice.server         - WARNING  - blueprint /optvar/cockpit_repos/demo1/blueprints/myvdc.yaml not executed because it doesn't have a valid forma
```
Please evaluate how we can give a more appropriate error message.

See the full traceback below.

It turns out that the error was in the `schema.capnp`:
```
@0xf7714934bdbd4021
struct Schema {
        jwt @0 :Text;
        cloudspaceID @1 :Int64 = 0;
        location @2 :Text;
        maxNumPublicIP @3 :Int64 = 1;
}
```

The error is the missing `;` in the first line.

When restarting AYS, without first correcting the error, we got another error, see the second stack trace here below.

After I having corrected the 'schema.capnpn' I still had to do a `ays repo destroy` in order to have it fully working.

#### Relevant stacktraces

**Before restarting AYS**:
```
[Thu07 16:08] - utils.py            :76  :j.atyourservice.server.blueprint - ERROR    - Service template actor1 not found. Can't execute this blueprint
[Thu07 16:08] - utils.py            :76  :j.atyourservice.server.blueprint - ERROR    - Service template actor1 not found. Can't execute this blueprint
[Thu07 16:08] - AtYourServiceRepo.py:493 :j.atyourservice.server         - WARNING  - blueprint /optvar/cockpit_repos/demo1/blueprints/myvdc.yaml not executed because it doesn't have a valid format
[Thu07 16:08] - ays_api.py          :472 :j.atyourservice.server         - ERROR    - Input Exception :
 ERROR: Service template actor1 not found. Can't execute this blueprint ((type:input.error)
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 468, in executeBlueprint
    message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 494, in blueprintExecute
    raise j.exceptions.Input(bp.valid_msg)
JumpScale9.errorhandling.JSExceptions.Input: ERROR: Service template actor1 not found. Can't execute this blueprint ((type:input.error)
2017-09-07 16:08:09 - (network)[INFO][127.0.0.1:48404]: POST http://localhost:5000/ays/repository/demo1/blueprint/myvdc.yaml  400 102
```

**After restarting AYS**:
```
[Thu07 16:19] - Service.py          :68  :j.atyourservice.server.service - INFO     - init service myspecialvdc from actor1
[Thu07 16:19] - ays_api.py          :472 :j.atyourservice.server         - ERROR    - Input Exception :
 ERROR: Could not load capnp schema for:actortemplate: /optvar/cockpit_repos/demo2/actorTemplates/actor1/:actor1
- path: /optvar/cockpit_repos/demo2/actorTemplates/actor1/
CapnpError:
/optvar/capnp/schema_f7714934bdbd402.capnp:1: failed: Parse error.
 ((source:ays.template type:input.error)
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/ActorTemplate.py", line 56, in schema
    return j.data.capnp.getSchemaFromText(self.schemaCapnpText, name="Schema")
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/capnp/Capnp.py", line 128, in getSchemaFromText
    schemas = self._getSchemas(schemaInText)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/capnp/Capnp.py", line 116, in _getSchemas
    schema = parser.load(path)
  File "capnp/lib/capnp.pyx", line 3251, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:65948)
capnp.lib.capnp.KjException: /optvar/capnp/schema_f7714934bdbd402.capnp:1: failed: Parse error.
stack: 0x7f5e67d516d8 0x7f5e67c5685b 0x7f5e67c56d95 0x7f5e67c6938f 0x7f5e67c6a283 0x7f5e67c57e96 0x7f5e67c8a8e7 0x7f5e67c8a9cb 0x7f5e67c8aef9 0x7f5e67c8af34 0x7f5e67c55693 0x7f5e67c56502 0x7f5e67c0aba6 0x7f5e67bf576d 0x4e9
bc7 0x524414

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 468, in executeBlueprint
    message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 495, in blueprintExecute
    msg = await bp.load(role=role, instance=instance, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 154, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 511, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 26, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 110, in _initFromActor
    msg = template.schema.new_message()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/ActorTemplate.py", line 62, in schema
    raise j.exceptions.Input(message=msg, level=1, source="ays.template", tags="", msgpub="")
JumpScale9.errorhandling.JSExceptions.Input: ERROR: Could not load capnp schema for:actortemplate: /optvar/cockpit_repos/demo2/actorTemplates/actor1/:actor1
- path: /optvar/cockpit_repos/demo2/actorTemplates/actor1/
CapnpError:
/optvar/capnp/schema_f7714934bdbd402.capnp:1: failed: Parse error.
 ((source:ays.template type:input.error)
2017-09-07 16:19:51 - (network)[INFO][127.0.0.1:48410]: POST http://localhost:5000/ays/repository/demo2/blueprint/myvdc.yaml  400 321
2017-09-07 16:21:47 - (network)[INFO][127.0.0.1:48412]: GET http://localhost:5000/ays/repository/demo2/blueprint?archived=False  200 23
[Thu07 16:21] - Service.py          :68  :j.atyourservice.server.service - INFO     - init service myspecialvdc from actor1
[Thu07 16:21] - Job.py              :66  :j.core.jobcontroller.job.6622a6ecfad9e9fc4ea931f07337601d - INFO     - job job: actor1!myspecialvdc (input) done sucessfuly
[Thu07 16:21] - ays_api.py          :482 :j.atyourservice.server         - ERROR    - Error during execution of the blueprint:
 /optvar/capnp/schema_f7714934bdbd402.capnp:1: failed: Parse error.
stack: 0x7f5e67d516d8 0x7f5e67c5685b 0x7f5e67c56d95 0x7f5e67c6938f 0x7f5e67c6a283 0x7f5e67c57e96 0x7f5e67c8a8e7 0x7f5e67c8a9cb 0x7f5e67c8aef9 0x7f5e67c8af34 0x7f5e67c55693 0x7f5e67c56502 0x7f5e67c0aba6 0x7f5e67bf576d 0x4e9
bc7 0x524414
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 468, in executeBlueprint
    message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 495, in blueprintExecute
   message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 495, in blueprintExecute
    msg = await bp.load(role=role, instance=instance, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 154, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 511, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 26, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 125, in _initFromActor
    self._validate_service_args(args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 155, in _validate_service_args
    schema = j.data.capnp.getSchemaFromText(self.model.dbobj.dataSchema)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/capnp/Capnp.py", line 128, in getSchemaFromText
    schemas = self._getSchemas(schemaInText)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/capnp/Capnp.py", line 116, in _getSchemas
    schema = parser.load(path)
  File "capnp/lib/capnp.pyx", line 3251, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:65948)
capnp.lib.capnp.KjException: /optvar/capnp/schema_f7714934bdbd402.capnp:1: failed: Parse error.
stack: 0x7f5e67d516d8 0x7f5e67c5685b 0x7f5e67c56d95 0x7f5e67c6938f 0x7f5e67c6a283 0x7f5e67c57e96 0x7f5e67c8a8e7 0x7f5e67c8a9cb 0x7f5e67c8aef9 0x7f5e67c8af34 0x7f5e67c55693 0x7f5e67c56502 0x7f5e67c0aba6 0x7f5e67bf576d 0x4e9
bc7 0x524414
```

#### Blueprint
```yaml
actor1__myspecialvdc:
  jwt: 'eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiI3UDYwNHQ0cjJnQmQwOUZ2VjJrcEl5WXI4Rjh5IiwiZXhwIjoxNTA0ODA1NTM5LCJpc3MiOiJpdHN5b3VvbmxpbmUiLCJzY29wZSI6WyJ1c2VyOmFkbWluIl0sInVzZXJuYW1lIjoieXZlc3RlY2gifQ.b7C9WHTpdNKh8yu5Gv03A6TvtzxC-hLezoVdEEJcSHV_al1Et3eXVl9juREYyiomLeqsnB_ICGesqt5HPx4ppoD2qcwZLdzehWGLJkEzD3fIDRJVvtCFljiVHC-BaBWp'
  location: "be-gen-1"
  maxNumPublicIP: 3

actions:
  - action: install
```

#### actions.py
```python
from js9 import j

def install(job):
    service = job.service
    data  = service.model.data

    cl = j.clients.openvcloud.get("be-gen-1.demo.greenitglobe.com", jwt=data.jwt)

    acc = cl.account_get("myaccount")

    cs = acc.space_get(name=service.model.dbobj.name,
                       location=data.location,
                       maxNumPublicIP=data.maxNumPublicIP)

    data.cloudspaceID = cs.model['id']

    service.model.save()
```

#### config.yaml
```
doc:
  property:
       - jwt: ''
       - cloudspaceID: ''
       - location: ''
       - maxNumPublicIP: ''
```

**Comment by rkhamis** [comment]
Is `ERROR: Could not load capnp schema for:actortemplate: /optvar/cockpit_repos/demo2/actorTemplates/actor1/:actor1` not descriptive enough?

**Comment by rkhamis** [comment]
From the other end, `actor1` template not found is just a byproduct

**Comment by rkhamis** [comment]
And having applied your scenario, when you first try to load an actor with a bad schema, you get:
```
ays blueprint
error during execution of the blueprint 1: ERROR: Could not load capnp schema for:actortemplate: /optvar/cockpit_repos/wrongschema/actorTemplates/wrong/:wrong
- path: /optvar/cockpit_repos/wrongschema/actorTemplates/wrong/
CapnpError:
/optvar/capnp/schema_f7714934bdbd402.capnp:1: failed: Parse error.
 ((source:ays.template type:input.error)
```

Which seems very explicit.

What I do feel needs work, though, is that you had to destroy. `ays actor update` should fix it.

I'll keep this issue open for that.

**Comment by despiegk** [comment]
ays 9.3.0 will resolve this
