### ISSUE TITLE
harden redis client

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#244]
#### Installation information

- jumpscale version: 9.1.2

#### Detailed description

If redis tries to hget a deleted item, it will crash on decoding it

#### Relevant stacktraces
```
ERROR:asyncio:Exception in callback <bound method AtYourServiceFactory.cleanup of <JumpScale9AYS.ays.AtYourServiceFactory.AtYourServiceFactory object at 0x7fe221443da0>>
handle: <TimerHandle cancelled None created at /opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py:74>
source_traceback: Object created at (most recent call last):
  File "main.py", line 76, in <module>
    main()
  File "/opt/jumpscale9/lib/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/jumpscale9/lib/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/jumpscale9/lib/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/jumpscale9/lib/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 72, in main
    sanic_app.run(debug=debug, host=host, port=port, workers=1)
  File "/opt/jumpscale9/lib/sanic/app.py", line 595, in run
    serve(**server_settings)
  File "/opt/jumpscale9/lib/sanic/server.py", line 527, in serve
    loop.run_forever()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 74, in cleanup
    self._cleanupHandle = self.loop.call_later(sleep, self.cleanup)
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 186, in uvloop.loop.TimerHandle._run (uvloop/loop.c:50596)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 64, in cleanup
    jobs = j.core.jobcontroller.db.jobs.find()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/models/JobsCollections.py", line 74, in find
    for key in self.list(actor, service, action, state, serviceKey, fromEpoch, toEpoch, tags):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/models/JobsCollections.py", line 54, in list
    res0 = self._index.list(regex, returnIndex=True)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/key_value_store/redis_store.py", line 109, in list
    key = self.redisclient.hget(self._indexkey, item).decode()
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by john-kheir** [comment]
Verified
