### ISSUE TITLE
can't start ays 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [Jumpscale/ays9#255]
#### Installation information

- jumpscale version: master : 120b4d726
- operating system: ubuntu 16

#### Detailed description
can't start ays

#### Steps to reproduce
run command ays start

#### Relevant stacktraces
```
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 72, in main
    sanic_app.run(debug=debug, host=host, port=port, workers=1)
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 595, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 506, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 419, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25632)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109361)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112669)
  File "main.py", line 58, in init_ays
    key_path = local_prefab.ssh.keygen(name='ays_repos_key').split(".pub")[0]
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabSSH.py", line 109, in keygen
    d = self.prefab.user.check(user)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabUser.py", line 93, in check
    s = self.prefab.core.sudo("getent shadow | egrep '^%s:' | awk -F':' '{print $2}'" % (results['name']))
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1094, in sudo
    return self.run(cmd, die=die, showout=showout)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1142, in run
    rc, out, err = self.executor.execute(cmd, checkok=checkok, die=die, showout=showout, env=env, timeout=timeout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorLocal.py", line 47, in execute
    outputStderr=outputStderr, timeout=timeout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/sal/process/SystemProcess.py", line 204, in execute
    raise RuntimeError("Could not execute cmd:\n'%s'\nerr:\n%s" % (command, err))
RuntimeError: Could not execute cmd:
'bash -c 'set -e;apt-get install sudo && echo '' | sudo -SE -p '' bash -c "source /root/.jsenv.sh; getent shadow | egrep '^root:' | awk -F':' '{print $2}'"''
err:
}": -c: line 0: unexpected EOF while looking for matching `"'
}": -c: line 1: syntax error: unexpected end of file
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
```

**Comment by john-kheir** [comment]
Verified
