### ISSUE TITLE
ovc.node trying to create machine with wrong size

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#260]
#### Installation information

- jumpscale version: master/Docker
- operating system: ubuntu

#### Detailed description

See the below blueprint, which includes an error:

```yaml
node.ovc__PTJEORCBUF:
   vdc: "xojbSf8JDttvu3SHsh3C"
   bootdiskSize: 10
   memory: 10
   osImage: Ubuntu 16.04 x64
 
actions:
  - action: install
```

The value of 10 for memory is incorrect.

But when executing a run using this blueprint, we end up with the following run:

![screen shot 2017-09-18 at 16 25 37](https://user-images.githubusercontent.com/13795109/30546851-070a6af2-9c8e-11e7-9c2e-dcdca9db5980.png)

Checking the details shows: 
```bash
JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7
```

Which is strange because when checking all available sizes for the cloud space (with id = 1050) using https://be-gen-1.demo.greenitglobe.com/system/ActorApi?group=cloudapi#/cloudapi__sizes, there is no entry for 10:

```json
[
  {
    "description": "",
    "disks": [
      10,
      20,
      50,
      100,
      250,
      500,
      1000,
      2000
    ],
    "vcpus": 1,
    "memory": 512,
    "id": 1,
    "name": ""
  },
  {
    "description": "",
    "disks": [
      10,
      20,
      50,
      100,
      250,
      500,
      1000,
      2000
    ],
    "vcpus": 1,
    "memory": 1024,
    "id": 2,
    "name": ""
  },
  {
    "description": "",
    "disks": [
      10,
      20,
      50,
      100,
      250,
      500,
      1000,
      2000
    ],
    "vcpus": 2,
    "memory": 4096,
    "id": 3,
    "name": ""
  },
  {
    "description": "",
    "disks": [
      10,
      20,
      50,
      100,
      250,
      500,
      1000,
      2000
    ],
    "vcpus": 4,
    "memory": 8192,
    "id": 4,
    "name": ""
  },
  {
    "description": "",
    "disks": [
      10,
      20,
      50,
      100,
      250,
      500,
      1000,
      2000
    ],
    "vcpus": 8,
    "memory": 16384,
    "id": 5,
    "name": ""
  },
  {
    "description": "",
    "disks": [
      10,
      20,
      50,
      100,
      250,
      500,
      1000,
      2000
    ],
    "vcpus": 2,
    "memory": 2048,
    "id": 6,
    "name": ""
  },
  {
    "id": 7,
    "vcpus": 2,
    "disks": [
      50
    ],
    "name": "2-8192-50-120",
    "memory": 8192
  },
  {
    "id": 8,
    "vcpus": 4,
    "disks": [
      50
    ],
    "name": "4-16384-50-120",
    "memory": 16384
  }
]
```

Apparently `size_id = space.size_find_id(service.model.data.memory)` default to 7 in that case.

#### Steps to reproduce

Blueprints:

```yaml
node.ovc__PTJEORCBUF:
   vdc: "xojbSf8JDttvu3SHsh3C"
   bootdiskSize: 10
   memory: 10
   osImage: Ubuntu 16.04 x64
 
actions:
  - action: install
```

Checking the Cloud Broker Portal we see this:
https://be-gen-1.demo.greenitglobe.com/grid/audit?id=c28ff5a8-4fe3-4e5e-a0d7-251137659ca4

![screen shot 2017-09-18 at 16 36 51](https://user-images.githubusercontent.com/13795109/30547439-8ed5bc9c-9c8f-11e7-8f94-ee797af9c695.png)

#### Relevant stacktraces

```bash
2017/09/18 13:35:35 - trace: JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 13:35:35 - errormsg: Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/ec280cde588ef64173154834b476bbb6.py", line 613, in install
    machine = _create_machine(service, space)
  File "/tmp/actions/node.ovc/ec280cde588ef64173154834b476bbb6.py", line 662, in _create_machine
    stackId=service.model.data.stackID if service.model.data.stackID >= 0 else None)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 445, in machine_create
    cloudspaceId=self.id, name=name, sizeId=sizeId, imageId=imageId, disksize=disksize, datadisks=datadisks)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 44, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 13:35:53 - trace: JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 13:35:53 - errormsg: Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/ec280cde588ef64173154834b476bbb6.py", line 613, in install
    machine = _create_machine(service, space)
  File "/tmp/actions/node.ovc/ec280cde588ef64173154834b476bbb6.py", line 662, in _create_machine
    stackId=service.model.data.stackID if service.model.data.stackID >= 0 else None)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 445, in machine_create
    cloudspaceId=self.id, name=name, sizeId=sizeId, imageId=imageId, disksize=disksize, datadisks=datadisks)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 44, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 13:36:31 - trace: JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 13:36:31 - errormsg: Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/ec280cde588ef64173154834b476bbb6.py", line 613, in install
    machine = _create_machine(service, space)
  File "/tmp/actions/node.ovc/ec280cde588ef64173154834b476bbb6.py", line 662, in _create_machine
    stackId=service.model.data.stackID if service.model.data.stackID >= 0 else None)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 445, in machine_create
    cloudspaceId=self.id, name=name, sizeId=sizeId, imageId=imageId, disksize=disksize, datadisks=datadisks)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 44, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 13:37:43 - trace: JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 13:37:43 - errormsg: Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/ec280cde588ef64173154834b476bbb6.py", line 613, in install
    machine = _create_machine(service, space)
  File "/tmp/actions/node.ovc/ec280cde588ef64173154834b476bbb6.py", line 662, in _create_machine
    stackId=service.model.data.stackID if service.model.data.stackID >= 0 else None)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 445, in machine_create
    cloudspaceId=self.id, name=name, sizeId=sizeId, imageId=imageId, disksize=disksize, datadisks=datadisks)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 44, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 13:42:51 - trace: JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 13:52:59 - trace: JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
2017/09/18 14:23:04 - trace: JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Disk size of 10GB is invalid for sizeId 7.
```

**Comment by ahussein** [comment]
In the openvcloud client code here https://github.com/Jumpscale/lib9/blob/master/JumpScale9Lib/clients/openvcloud/Client.py#L458 
The provided memory size is assumed to be in GB if its less than 100 so its multiplied by 1024 and then the highest size that match the memory size matches and the sizeId is returned. Meaning that sizeId 7 is returned because the sizeId 7 which has a memory size of 8192 matches the given memory size.
In the same time the the given disk size of 10 GB does not match the disk sizes available in in sizeId 7 which is 50.

This is obviously not an AYS problem. You need to file a ticket in the Openvcloud client library or in the openvcloud backend.

You can also move on by setting the correct disk size (50) in the case you want a memory size of 10 GB. If you did not specify the memory size in the bp, it will default to 2 GB which will work just fine.

I propose to close this ticket.

**Comment by rkhamis** [comment]
I think we need to update the documentation on this to contain what @ahussein just explained then close

**Comment by yveskerwyn** [comment]
PR: https://github.com/Jumpscale/ays9/pull/300
