### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode' 

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/ays9#263]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Detailed description
I saw this stacktrace passing by in AYS logs after I asked for a deletion of a vdisk on be-g8-3

#### Steps to reproduce
Don't have procedure to reproduce yet.

#### Relevant stacktraces
```
ERROR:sanic:Traceback (most recent call last):                                                                               
  File "/opt/jumpscale9/lib/sanic/app.py", line 503, in handle_request   
    response = await response                                                                                                                                                        
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 133, in get                                
    return await auth(request, ays_api.getJob(request, jobid, repository))             
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 14, in auth                                            
    return await func                                                                                                        
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 316, in getJob
    jobs = repo.jobsList()                                           
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 578, in jobsList                   
    for job in j.core.jobcontroller.db.jobs.find(serviceKey=key):       
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/models/JobsCollections.py", line 74, in find                                                                    
    for key in self.list(actor, service, action, state, serviceKey, fromEpoch, toEpoch, tags):    
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/models/JobsCollections.py", line 54, in list                             
    res0 = self._index.list(regex, returnIndex=True)          
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/key_value_store/redis_store.py", line 109, in list                                                                   
    key = self.redisclient.hget(self._indexkey, item).decode()
    AttributeError: 'NoneType' object has no attribute 'decode' 
```

**Comment by rkhamis** [comment]
already fixed in https://github.com/Jumpscale/core9/pull/69
