### ISSUE TITLE
Wrong path in when using j.tools.prefab.local.apps.portal.start()

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#269]
#### Installation information

- jumpscale version: master
- operating system:

#### Detailed description

When trying to start to portal using `j.tools.prefab.local.apps.portal.start()` I get this problem in the tmux window:
```
FileNotFoundError: [Errno 2] No such file or directory: Path('/opt/jumpscale9/app//portals/portalbase')
[Errno 2] No such file or directory: Path('/opt/jumpscale9/app//portals/portalbase')
```

`app/` needs to be `apps`.

#### Steps to reproduce

Check the Docker container on 172.25.0.238, for which you'll need to join ZT 17d709436cdf03a2.

This Docker container is hosted on https://be-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1387

#### Relevant stack traces

```bash
root@js9:~# echo **START**;cd /opt/jumpscale9/apps/portals/main && python3 portal_start.py && echo **OK** || echo **ERROR**
**START**
('Monitoring', '/opt/jumpscale9/apps/portals/main/base')
Traceback (most recent call last):
  File "portal_start.py", line 40, in <module>
    cli(obj={})
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "portal_start.py", line 19, in cli
    start()
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "portal_start.py", line 34, in start
    server = j.portal.tools.server.get()
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalServerFactory.py", line 19, in get
    return PortalServer.PortalServer()
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalServer.py", line 138, in __init__
    self.loadConfig()
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalServer.py", line 195, in loadConfig
    self.appdir.chdir()
  File "/usr/local/lib/python3.5/dist-packages/path.py", line 1368, in chdir
    os.chdir(self)
FileNotFoundError: [Errno 2] No such file or directory: Path('/opt/jumpscale9/app//portals/portalbase')
[Errno 2] No such file or directory: Path('/opt/jumpscale9/app//portals/portalbase')
**ERROR**
```

**Comment by dinosn** [comment]
Hi adding one thing here i temporary resolved the issue by linking the app to apps 
```
ln -fs /opt/jumpscale9/app/ /opt/jumpscale9/apps 
```

**Comment by ahussein** [comment]
Cannot reproduce using master branch. Also our building process for the portal makes sure that we can start the portal and the build is green.
The code will use the /opt/jumpscale9/app as the APP dir and that will work fine. We probably should change it to apps but as far as i can see this is not stopping the portal from starting.
the JSAPPDIR is configured to be /opt/jumpscale9/app as you can see from 
```
In [2]: j.dirs.JSAPPSDIR
Out[2]: '/opt/jumpscale9/app/'
```

**Comment by ahmedelsayed-93** [comment]
Cannot reproduce
### software version
9.2
