### ISSUE TITLE
Update templates failed from ays portal app

### ISSUE THREAD

**Issue by arahmanhamdy** [Jumpscale/ays9#322]
#### Installation information

- jumpscale version: master
- operating system:ubuntu 16.04

#### Detailed description
When use ays portal app, the update templates button give error

#### Steps to reproduce
login into portal (i.e localhost:8200)
from actor templates menu choose actions>update teamplates

#### Relevant stacktraces
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalRest.py", line 241, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
  File "/opt/code/github/jumpscale/ays9/apps/ays__tools/methodclass/ays_tools.py", line 80, in templatesUpdate
    cl.updateTemplates(repo)
AttributeError: 'AysService' object has no attribute 'updateTemplates'
***ERROR***:Execute method POST_ays_tools_templatesUpdate failed.
method was:/restmachine/ays/tools/templatesUpdate : method /restmachine/ays/tools/templatesUpdate from ip 172.17.0.1 with params
172.17.0.1 - - [2017-10-10 14:12:28] "POST /restmachine/ays/tools/templates
Update HTTP/1.1" 500 177 0.187771
path:AYS/ActorTemplate

**Comment by arahmanhamdy** [comment]
duplicates #185
