### ISSUE TITLE
Can't start ays 

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/ays9#33]
## Issue 
```
2017-06-15 08:59:08 - (sanic)[INFO]: Goin' Fast @ http://127.0.0.1:5000
2017-06-15 08:59:08 - (sanic)[ERROR]: Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 398, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 354, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25632)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109361)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112669)
  File "main.py", line 49, in init_ays
    j.atyourservice.server.debug = debug
AttributeError: 'AtYourService' object has no attribute 'server'
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 64, in main
    sanic_app.run(debug=debug, host=host, port=port, workers=1)
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 398, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 354, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25632)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109361)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112669)
  File "main.py", line 49, in init_ays
    j.atyourservice.server.debug = debug
AttributeError: 'AtYourService' object has no attribute 'server'
'AtYourService' object has no attribute 'server'
**ERROR**
```

## Software Version
4398aeff74b200d64ff31baacb9dbc1183799e5c

**Comment by ahussein** [comment]
Not an issue anymore
