### ISSUE TITLE
Capnp serialization error on Threefold orchestrator

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/ays9#343]
#### Installation information

- jumpscale version: master
- operating system: ubuntu-1604

#### Detailed description
While trying to updating the actors (```ays actor update```) a capnp related error is being reported and the ays action failed

#### Relevant stacktraces
```
root@tno-0001:/opt/var/cockpit_repos/itenv_orchestrator_nodes-0001# ays actor update
actor node.zero-os updated
actor erp_registration.odoo updated
error during update of actor healthcheck: unexpected error: kj/io.c++:236: failed: expected size <= (size_t)(array.end() - fillPos); ArrayOutputStream's backing array was not large enough for the data written.
stack: 0x7fa59d28955b 0x7fa59d2e5576 0x7fa59d288fd7 0x7fa59d289b7a 0x7fa59d1c5978 0x7fa59d1c5b03 0x7fa59d1790c3 0x7fa59d17932b 0x528084 0x528464 0x528464 0x528464 0x52cf19 0x528b3f 0x4e4bf3 0x529783 0x4e4bf3 0x529783 0x4e4bf3 0x529783 0x4e4bf3 0x4e1144 0x7fa59eabd69f 0x7fa59eb73f71 0x7fa59eb8c8be 0x7fa59eb90daa 0x7fa59eb8c85e 0x7fa59eb9000e 0x7fa59ebbeb74 0x7fa59ebbcbf0 0x7fa59eae8970
```

**Comment by ahussein** [comment]
@FastGeert Can you please add the stracktrace from ays9 server ? or add steps to reproduce ?

**Comment by rkhamis** [comment]
@ahussein like I told you, this doesn't show up consistently and we've been unable to reproduce...

the ays logs show:
```
source_traceback: Object created at (most recent call last):
  File "main.py", line 76, in <module>
    main()
  File "/opt/jumpscale9/lib/click/core.py", line 722, in call
    return self.main(*args, **kwargs)
  File "/opt/jumpscale9/lib/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/jumpscale9/lib/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/jumpscale9/lib/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 72, in main
    sanic_app.run(debug=debug, host=host, port=port, workers=1)
  File "/opt/jumpscale9/lib/sanic/app.py", line 595, in run
    serve(**server_settings)
  File "/opt/jumpscale9/lib/sanic/server.py", line 527, in serve
    loop.run_forever()
Traceback (most recent call last):
  File "capnp/lib/capnp.pyx", line 1242, in capnp.lib.capnp._DynamicStructBuilder.to_bytes_packed (capnp/lib/capnp.cpp:26217)
capnp.lib.capnp.KjException: src/kj/io.c++:229: failed: expected size <= (size_t)(array.end() - fillPos); ArrayOutputStream's backing array was not large enough for the data written.
stack: 0x7f4dfe243639 0x7f4dfe24726d 0x7f4dfe1f1d1c 0x7f4dfe24870b 0x7f4dfe1f6ca5 0x7f4dfe247ae6 0x7f4dfe1f6657 0x7f4dfe1f735a 0x7f4dfe140cf0 0x7f4dfe140e53 0x7f4dfe0f1a59 0x7f4dfe0f23db 0x528424 0x528814 0x528814 0x528814

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48380)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/Job.py", line 72, in _execute_cb
    job.save()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/Job.py", line 299, in save
    self.service.saveAll()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 332, in saveAll
    self.model.save()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/capnp/ModelBase.py", line 120, in save
    self._pre_save()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/models/ServiceModel.py", line 253, in _pre_save
    binary = self.data.to_bytes_packed()
  File "capnp/lib/capnp.pyx", line 1246, in capnp.lib.capnp._DynamicStructBuilder.to_bytes_packed (capnp/lib/capnp.cpp:26293)
capnp.lib.capnp.KjException: src/kj/io.c++:229: failed: expected size <= (size_t)(array.end() - fillPos); ArrayOutputStream's backing array was not large enough for the data written.
stack: 0x7f4dfe243639 0x7f4dfe24726d 0x7f4dfe1f1d1c 0
```

**Comment by ahussein** [comment]
So far, I cannot reproduce and I cannot figure out the root cause of the error. My recommendation is to keep this ticket open until we have a system where this is reproduced and then we can investigate more on the system.

**Comment by despiegk** [comment]
ays 9.3.0 will resolve this
