### ISSUE TITLE
AYS doesn't start in 9.2.0

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#350]
#### Installation information

- jumpscale version: 9.2.0 (master)
- operating system: Docker container > ZInstall_ays9

#### Steps to reproduce

use `ZInstall_ays9` to create a Docker container with JS9BRANCH=master
In the shell:
 `j.tools.prefab.local.apps.atyourservice.install()`
 `j.tools.prefab.local.apps.atyourservice.start()`

#### Relevant stacktraces

Full output:
```bash
2017-10-24 13:55:45 - (sanic)[INFO]: Goin' Fast @ http://localhost:5000
[Tue24 13:55] - PrefabCore.py       :1120:j.prefab.core                  - INFO     - PROFILECMD:source /root/.bash_profile; getent passwd | egrep '^root:' ; true
root:x:0:0:root:/root:/bin/bash
[Tue24 13:55] - PrefabCore.py       :1120:j.prefab.core                  - INFO     - PROFILECMD:source /root/.bash_profile; getent shadow | egrep '^root:' | awk -F':' '{print $2}'
root:*:17296:0:99999:7:::
[Tue24 13:55] - PrefabCore.py       :1120:j.prefab.core                  - INFO     - PROFILECMD:source /root/.bash_profile; ssh-keygen -q -t rsa -f /root/.ssh/ays_repos_key -N ''
[Tue24 13:55] - SSHClientFactory.py :478 :j.clients.ssh                  - INFO     - load ssh agent
[Tue24 13:55] - SSHClientFactory.py :160 :j.clients.ssh                  - INFO     - NO NEED TO ADD SSH_AUTH_SOCK to env
[Tue24 13:55] - SSHClientFactory.py :272 :j.clients.ssh                  - INFO     - load sshkey: /root/.ssh/ays_repos_key
Identity added: /root/.ssh/ays_repos_key (/root/.ssh/ays_repos_key)
Lifetime set to 86400 seconds
[Tue24 13:55] - TemplateRepo.py     :52  :j.atyourservice.server         - INFO     - reload actor templates repos

[Tue24 13:56] - TemplateRepo.py     :214 :j.atyourservice.server         - INFO     - reload actor templates from /opt/code/github/jumpscale/ays9
[Tue24 13:56] - TemplateRepo.py     :214 :j.atyourservice.server         - INFO     - reload actor templates from /opt/code/github/openvcloud/ays_templates
[Tue24 13:56] - TemplateRepo.py     :214 :j.atyourservice.server         - INFO     - reload actor templates from /opt/code/github/zero-os/0-orchestrator
[Tue24 13:56] - TemplateRepo.py     :214 :j.atyourservice.server         - INFO     - reload actor templates from /opt/code/github/zero-os/ays_template_g8os
[Tue24 13:56] - AtYourServiceRepo.py:30  :j.atyourservice.server         - INFO     - reload AYS repos
[Tue24 13:56] - AtYourServiceRepo.py:40  :j.atyourservice.server         - ERROR    - can't load repo at /opt/code/github/0-complexity/playenv/ays_github/: [Errno 2] No such file or directory: '/opt/code/github/0-complexity/playenv/ays_gi
thub/services/github_account!0-complexity/service.json'
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 37, in _load
    repo = AtYourServiceRepo(path, loop=self._loop)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 144, in __init__
    self._load_services()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 166, in _load_services
    Service.init_from_fs(aysrepo=self, path=service_path)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 51, in init_from_fs
    self._loadFromFS(path)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 299, in _loadFromFS
    model_json = j.data.serializer.json.load(j.sal.fs.joinPaths(path, "service.json"))
  File "/opt/code/github/jumpscale/core9/JumpScale9/data/serializers/SerializerBase.py", line 11, in load
    b = j.sal.fs.readFile(path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 1218, in readFile
    return self.fileGetContents(filename)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 1193, in fileGetContents
    with open(filename, encoding=encoding) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/code/github/0-complexity/playenv/ays_github/services/github_account!0-complexity/service.json'
[Tue24 13:56] - AtYourServiceRepo.py:40  :j.atyourservice.server         - ERROR    - can't load repo at /opt/code/github/0-complexity/playenv/ays_ovc_ostest/: [Errno 2] No such file or directory: '/opt/code/github/0-complexity/playenv/a$s_ovc_ostest/services/blueprint!mytestmachine/service.json'
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 37, in _load
    repo = AtYourServiceRepo(path, loop=self._loop)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 144, in __init__
    self._load_services()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 166, in _load_services
    Service.init_from_fs(aysrepo=self, path=service_path)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 51, in init_from_fs
    self._loadFromFS(path)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 299, in _loadFromFS
    model_json = j.data.serializer.json.load(j.sal.fs.joinPaths(path, "service.json"))
  File "/opt/code/github/jumpscale/core9/JumpScale9/data/serializers/SerializerBase.py", line 11, in load
    b = j.sal.fs.readFile(path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 1218, in readFile
    return self.fileGetContents(filename)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 1193, in fileGetContents
    with open(filename, encoding=encoding) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/code/github/0-complexity/playenv/ays_ovc_ostest/services/blueprint!mytestmachine/service.json'
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<ays_qa_tests> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<ays_cockpit> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<ays_github> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<ays_githuib_test> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<ays_internalit> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<ays_ovc_ostest> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<ays_ovh> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<ays_whmcs> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<docker_ovc> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<kvm_packet.net> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo1> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo2> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo3> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo4> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo5> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo_basicdelete> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo_consume> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo_delete_models> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo_longjobs> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo_recurring> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo_scheduler> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo_timeout> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<sample_repo_account> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<cl_cockpit> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<ays_g8os_packetnet> started
[Tue24 13:56] - RunScheduler.py     :75  :j.ays.runscheduler             - INFO     - RunScheduler<cockpit_g8os_testenv> started
2017-10-24 13:56:41 - (sanic)[ERROR]: Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 877, in uvloop.loop.Loop._create_server (uvloop/loop.c:19863)
  File "uvloop/handles/tcp.pyx", line 86, in uvloop.loop.TCPServer.bind (uvloop/loop.c:80140)
  File "uvloop/handles/streamserver.pyx", line 80, in uvloop.loop.UVStreamServer._fatal_error (uvloop/loop.c:78240)
  File "uvloop/handles/tcp.pyx", line 84, in uvloop.loop.TCPServer.bind (uvloop/loop.c:80082)
  File "uvloop/handles/tcp.pyx", line 26, in uvloop.loop.__tcp_bind (uvloop/loop.c:79340)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 509, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25636)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109407)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112715)
  File "uvloop/loop.pyx", line 1363, in create_server (uvloop/loop.c:27515)
  File "uvloop/loop.pyx", line 882, in uvloop.loop.Loop._create_server (uvloop/loop.c:20007)
OSError: [Errno 99] error while attempting to bind on address ('::1', 5000, 0, 0): cannot assign requested address
2017-10-24 13:56:41 - (sanic)[INFO]: Server Stopped
**OK**
root@js9:/opt/jumpscale9/app/atyourservice#
```

**Comment by rkhamis** [comment]
/etc/hosts had a bad value for localhost
