### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory 

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#351]
#### Installation information

- jumpscale version: master but pre-9.2.0, not updated yet
- operating system: Ubuntu 16.04 Docker container

#### Detailed description

AYS Server is running in a Docker container hosted on: 
https://be-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1387

After a while AYS Server typically needs to be restarted because of a "Cannot allocate memory" problem, see below for the stack trace.

#### Relevant stacktraces

```
2017-10-24 07:21:49 - (network)[INFO][172.25.235.38:48652]: POST http://172.25.0.238:5000/ays/repository  500 144
2017-10-24 09:25:51 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 29, in post
    return await auth(request, ays_api.createRepository(request))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 14, in auth
    return await func
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 91, in createRepository
    raise err
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 85, in createRepository
    repo = j.atyourservice.server.aysRepos.create(path, git_url=inputs['git_url'])
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 87, in create
    j.tools.executorLocal.execute('cd {};git init'.format(path))
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorLocal.py", line 47, in execute
    outputStderr=outputStderr, timeout=timeout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/sal/process/SystemProcess.py", line 94, in execute
    shell=useShell, env=os.environ, universal_newlines=False, cwd=cwd, bufsize=0, **popenargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by rkhamis** [comment]
We won't give a non-released version priority.
