### ISSUE TITLE
node.docker AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#368]
#### Installation information

- jumpscale version: 9.2.0 (master)
- operating system: Ubuntu 16.04

#### Detailed description

When executing the below `node.docker` blueprint I get: "AttributeError: 'str' object has no attribute 'get'":

![screen shot 2017-11-03 at 11 29 35](https://user-images.githubusercontent.com/13795109/32369681-655d6e18-c08a-11e7-8c2f-289d25230f0f.png)

#### Steps to reproduce

Two blueprints are in play here:
- the first one to create VDC, VM and install the Docker daemon - this works perfectly
- the second to create Docker container - this one fails to execute

First blueprint:
```yaml
g8client__g8:
  url: 'se-gen-1.demo.greenitglobe.com'
  jwt: '...'
  account: 'myaccount'

vdc__myvdc:
  g8client: 'g8'
  location: 'se-gen-1'

disk.ovc__disk1:
  size: 5
  type: "D"
  maxIOPS: 200

node.ovc__myvm:
  vdc: myvdc
  bootdisk.size: 50
  memory: 2
  os.image: 'Ubuntu 16.04 x64'
  ports:
    - '2210:22'
  disk:
    - 'disk1'

app_docker__dockerd:
  os: 'myvm'

actions:
  - action: install
```

Second blueprint:
```yaml
node.docker__apache:
  image: 'bitnami/apache'
  ports:
    - "80"
  os: 'myvm'

actions:
  action: install
```

 
#### Relevant stacktraces

```bash
[Fri03 10:14] - ays_api.py          :555 :j.atyourservice.server         - ERROR    - Error during execution of the blueprint:
 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 541, in executeBlueprint
    message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 495, in blueprintExecute
    msg = await bp.load(role=role, instance=instance, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 62, in load
    force0 = bool(actionModel.get('force', False))
AttributeError: 'str' object has no attribute 'get'
2017-11-03 10:14:54 - (network)[INFO][127.0.0.1:60580]: POST http://localhost:5000/ays/repository/docker/blueprint/container.yaml  500 47
```

**Comment by despiegk** [comment]
ays 9.3.0 will resolve this

**Comment by yveskerwyn** [comment]
OK works now, error was in my second blueprint:
```yaml
actions:
  action: install
```

Should be:
```yaml
actions:
  - action: install
```
