### ISSUE TITLE
AYS Server in error loop, and SSH to host times out

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#372]
#### Installation information

https://se-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1207

- jumpscale version: 9.2.0
- operating system: Ubuntu 16.04

Error loop (screenshot from end-user portal):

<img width="721" alt="screen shot 2017-11-06 at 20 36 21" src="https://user-images.githubusercontent.com/13795109/32460258-7cfb1296-c332-11e7-98c8-af4b9a700914.png">

Not sure how to analyse, tips?

**Comment by yveskerwyn** [comment]
Here's the looping error:
```bash
2017-11-06 20:01:27 - (network)[INFO][192.168.103.249:56778]: GET http://192.168.103.252:5000/machine/system/contentmanager/checkEvents?cursor=1  404 73
2017-11-06 20:01:30 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 493, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/usr/local/lib/python3.5/dist-packages/sanic/router.py", line 307, in get
    return self._get(request.path, request.method, '')
  File "/usr/local/lib/python3.5/dist-packages/sanic/router.py", line 356, in _get
    raise NotFound('Requested URL {} not found'.format(url))
sanic.exceptions.NotFound: Requested URL /machine/system/contentmanager/checkEvents not found
```

**Comment by zaibon** [comment]
/machine/system/contentmanager/checkEvents is not an url that Ays server handles. It looks more like a portal URL. Problem in configuration?

**Comment by yveskerwyn** [comment]
Yes indeed it was an issue in my Caddy config
