### ISSUE TITLE
Installing ays9 on MacOS fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#390]
#### Installation information

- jumpscale version: master (9.3.0)
- operating system: MacOS

#### Detailed description

When executing `pip3 install -e .` in the updated repo `/Users/yves/code/github/jumpscale/ays9` I get the following error:

```
Command "/usr/local/opt/python3/bin/python3.6 -c "import setuptools, tokenize;__file__='/Users/yves/code/github/jumpscale/ays9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/yves/code/github/jumpscale/ays9/
```

What does this mean?

**Comment by arahmanhamdy** [comment]
@yveskerwyn we have tried to install js9 on mac and it has been installed successfully, could you clarify if you still have the issue?

**Comment by yveskerwyn** [comment]
I'll have to retry, will do that later today

**Comment by yveskerwyn** [comment]
just tried again, when executing `pip3 install -e` I got the below:

```bash
(js9) [yves@yves-macbook-pros-MacBook-Pro portal9]$ git pull
Already up to date.
(js9) [yves@yves-macbook-pros-MacBook-Pro portal9]$ pip3 install -e .
Obtaining file:///Users/yves/code/github/jumpscale/portal9
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1025, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 558, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 432, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (redis 2.10.6 (/usr/local/lib/python3.6/site-packages), Requirement.parse('redis==2.10.5'), {'JumpScale9Portal'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 521, in _prepare_file
    req_to_install.check_if_exists()
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1036, in check_if_exists
    self.req.name
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 558, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 432, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (redis 2.10.6 (/usr/local/lib/python3.6/site-packages), Requirement.parse('redis==2.10.5'), {'JumpScale9Portal'})
```

**Comment by hossamabdullah** [comment]
You have a newer version of redis, you need to remove it so the code will be able to install the right one
