### ISSUE TITLE
AYS Server hangs with OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#392]
#### Installation information

- jumpscale version: 9.2.0
- operating system: Ubuntu 16.04

https://se-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1207

#### Detailed description

After a while AYS server stops functioning because of memory problems.

#### Steps to reproduce

Just use the AYS server for 2 weeks and you'll end up with this problem.

#### Relevant stacktraces

```
2017-11-27 13:28:48 - (network)[INFO][82.143.119.106:15818]: POST http://195.143.34.162:5000/ays/repository  500 144
2017-11-27 13:43:08 - (network)[INFO][127.0.0.1:35614]: GET http://localhost:5000/ays/repository  200 38115
2017-11-27 13:43:19 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 31, in post
    return await auth(request=request, funcname='createRepository')
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 16, in auth
    return await func(**kwargs)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 95, in createRepository
    raise err
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 89, in createRepository
    repo = j.atyourservice.server.aysRepos.create(path, git_url=inputs['git_url'])
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 87, in create
    j.tools.executorLocal.execute('cd {};git init'.format(path))
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/executor/ExecutorLocal.py", line 47, in execute
    outputStderr=outputStderr, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/sal/process/SystemProcess.py", line 95, in execute
    **popenargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by yveskerwyn** [comment]
let's close for now
