### ISSUE TITLE
AYS requires a restart to in order to re-execute a run succesfully, after destroying the repo

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#396]
#### Installation information

- jumpscale version: 9.2.0
- operating system: Ubuntu 16.0.4
- AYS Server:  https://se-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1207

#### Detailed description

When executing a run for the below blueprint both the VDC and the VM get successfully created.

When you then:
- Delete the VM - using the Cloud Broker Portal
- Destroy the repository - using `ays repo destroy`
- Re-execute the blueprint
- Start a new run

The VM creation succeeds but step 3 errors. The only way to get it the work is to firs restart AYS completelly.

Screenshot before the time out:
<img width="1530" alt="screen shot 2017-12-04 at 20 38 01" src="https://user-images.githubusercontent.com/13795109/33572461-4b123e6e-d933-11e7-9f0f-80749aeb1984.png">

#### Steps to reproduce

Following blueprint was used:

```yaml
g8client__uk:
  url: 'uk-ln-vt-1.g8.gigukportal.tech'
  jwt: '...'
  account: 'Account_of_Artilium'

vdc__partnerportals:
  g8client: 'uk'
  location: 'uk-ln-vt-1'

node.ovc__pphost:
    vdc: partnerportals
    bootdisk.size: 50
    memory: 4
    os.image: 'Ubuntu 16.04 x64'
    ports:
      - '2210:22'

partnerportal__mypp:
  os: 'pphost'
  vars:
    - 'var1="hello"'
    - 'var2="world"'
  url: 'https://docs.google.com/document/d/13sjWnnp_DZqChphna7SuQ3P7XaIe-P2Xdmwus_IkFpc'

actions:
  - action: install
```

#### Relevant stacktraces

```python
[Mon04 19:51] - Job.py              :29  :j.core.jobcontroller.job.ec97a0ee99f5dc3bb5a0a6030e4240e5 - INFO     - job: node.ovc!pphost (install) took 88.31925368309021 sec to execute
[Mon04 19:51] - Job.py              :70  :j.core.jobcontroller.job.ec97a0ee99f5dc3bb5a0a6030e4240e5 - ERROR    - job: node.ovc!pphost (install) failed:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/94df8ab43629ae637f98da9ad2e57b5b.py", line 622, in install
    raise e
  File "/tmp/actions/node.ovc/94df8ab43629ae637f98da9ad2e57b5b.py", line 611, in install
    prefab = _check_ssh_authorization(service, machine)
  File "/tmp/actions/node.ovc/94df8ab43629ae637f98da9ad2e57b5b.py", line 346, in _check_ssh_authorization
    prefab = _ssh_authorize(service, vm_info)
  File "/tmp/actions/node.ovc/94df8ab43629ae637f98da9ad2e57b5b.py", line 21, in _ssh_authorize
    executor.prefab.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabSSH.py", line 133, in authorize
    d = self.prefab.user.check(user, need_passwd=False)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabUser.py", line 82, in check
    _, d, _ = self.prefab.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1108, in run
    cmd = self.replace(cmd)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 275, in replace
    args2 = self.getArgsDict()
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 307, in getArgsDict
    args["HOSTNAME"] = self.hostname
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 597, in hostname
    return self.cache.get("hostname", get)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/data/cache/Cache.py", line 115, in get
    val = method(**kwargs)
File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 594, in get
    rc, out, err = self.run("cat %s" % hostfile, showout=False, replaceArgs=False)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1131, in run
    cmd = self.sudo_cmd(cmd, shell=shell)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1167, in sudo_cmd
    if "darwin" in self.prefab.platformtype.osname:
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/core/PlatformTypes.py", line 184, in osname
    rc, _, err = self.executor.execute("which %s" % pkgman, showout=False, die=False, checkok=False)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/executor/ExecutorSSH.py", line 237, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/clients/ssh/SSHClient.py", line 214, in execute
    ch = self.transport.open_session()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 732, in open_session
    timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 856, in open_channel
    raise e
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 1821, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 423, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 276, in read_all
    raise EOFError()
EOFError
[Mon04 19:51] - RunStep.py          :84  :j.atyourservice.server         - ERROR    - job: node.ovc!pphost (install) failed:

[Mon04 19:51] - RunStep.py          :87  :j.atyourservice.server         - INFO     - runstep 4: error
[Mon04 19:51] - Run.py              :162 :j.atyourservice.server         - ERROR    - error during execution of step 4 in run 5ebaeec20080cc4138ae6db03246857a
Error of job: node.ovc!pphost (install):
*TRACEBACK*********************************************************************************
job: node.ovc!pphost (install) failed:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/94df8ab43629ae637f98da9ad2e57b5b.py", line 622, in install
    raise e
  File "/tmp/actions/node.ovc/94df8ab43629ae637f98da9ad2e57b5b.py", line 611, in install
    prefab = _check_ssh_authorization(service, machine)
  File "/tmp/actions/node.ovc/94df8ab43629ae637f98da9ad2e57b5b.py", line 346, in _check_ssh_authorization
    prefab = _ssh_authorize(service, vm_info)
  File "/tmp/actions/node.ovc/94df8ab43629ae637f98da9ad2e57b5b.py", line 21, in _ssh_authorize
    executor.prefab.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabSSH.py", line 133, in authorize
    d = self.prefab.user.check(user, need_passwd=False)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabUser.py", line 82, in check
    _, d, _ = self.prefab.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1108, in run
    cmd = self.replace(cmd)
File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 275, in replace
    args2 = self.getArgsDict()
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 307, in getArgsDict
    args["HOSTNAME"] = self.hostname
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 597, in hostname
    return self.cache.get("hostname", get)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/data/cache/Cache.py", line 115, in get
    val = method(**kwargs)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 594, in get
    rc, out, err = self.run("cat %s" % hostfile, showout=False, replaceArgs=False)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1131, in run
    cmd = self.sudo_cmd(cmd, shell=shell)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1167, in sudo_cmd
    if "darwin" in self.prefab.platformtype.osname:
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/core/PlatformTypes.py", line 184, in osname
    rc, _, err = self.executor.execute("which %s" % pkgman, showout=False, die=False, checkok=False)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/executor/ExecutorSSH.py", line 237, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/clients/ssh/SSHClient.py", line 214, in execute
    ch = self.transport.open_session()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 732, in open_session
    timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 856, in open_channel
    raise e
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 1821, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 423, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 276, in read_all
    raise EOFError()
EOFError
EOFError


******************************************************************************************
```

**Comment by khaledkbadr** [comment]
When I was inspecting that issue I found out that if I restarted ays server the run succeeds with flying colors. To me it looks something in `ays repo destroy` is not done correctly. But of course, it needs more investigation/debugging.

**Comment by ahussein** [comment]
https://github.com/openvcloud/ays_templates/tree/ays_396
https://github.com/Jumpscale/lib9/tree/ays_396
https://github.com/Jumpscale/core9/tree/ays_396

**Comment by ahmedelsayed-93** [comment]
issue still exists 
i tried the same scenario using this blueprint 
```
g8client__env:
    url: 'be-g8-3.demo.greenitglobe.com'
    login: '....'
    password: '....'
    account: 'myaccount'

vdc__mycs:
    description: 'vdc for demo'
    g8client: 'env'
    account: 'myaccount'
    location: 'be-g8-3'

node.ovc__myvm:
    bootdisk.size: 50
    os.image: 'Ubuntu 16.04 x64'

actions:
  - action: install
  - action: test_create
    actor: myvm
    service: mycs
```
and i got this error 
```
[Thu11 07:46] - Job.py              :29  :j.core.jobcontroller.job.eff8b8c46d335ba52dea65ea54fcd104 - INFO     - job: vdc!mycs (install) took 63.3124885559082 sec to execute
[Thu11 07:46] - Job.py              :70  :j.core.jobcontroller.job.eff8b8c46d335ba52dea65ea54fcd104 - ERROR    - job: vdc!mycs (install) failed:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdc/f628ce5b41937865adb62b259b1a3138.py", line 110, in install
    raise j.exceptions.Timeout("VDC not yet deployed")
JumpScale9.errorhandling.JSExceptions.Timeout: ERROR: VDC not yet deployed ((type:timeout)
[Thu11 07:46] - RunStep.py          :84  :j.atyourservice.server         - ERROR    - job: vdc!mycs (install) failed:
ERROR: VDC not yet deployed ((type:timeout)
[Thu11 07:46] - RunStep.py          :87  :j.atyourservice.server         - INFO     - runstep 3: error
[Thu11 07:46] - Run.py              :162 :j.atyourservice.server         - ERROR    - error during execution of step 3 in run cc044e4be3238e70fee948124c2b39a3
Error of job: vdc!mycs (install):
*TRACEBACK*********************************************************************************
VDC not yet deployed

```

**Comment by ahussein** [comment]
code is not merged to development yet.
