### ISSUE TITLE
Unable to start AYS in a Docker container

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#418]
#### Installation information

- jumpscale version: 9.2.1
- operating system:  Ubunutu 16.04 (Docker container)

#### Detailed description

Using following Docker image: https://cloud.docker.com/app/jumpscale/repository/docker/jumpscale/ays-server/general

#### Steps to reproduce

In JS interactive shell on the Docker container:
```python
j.tools.prefab.local.js9.atyourservice.start()
```

No errors, but when checking the TMUX:

![screen shot 2018-02-28 at 10 30 55](https://user-images.githubusercontent.com/13795109/36780399-31502756-1c73-11e8-8940-bb750c5aac4a.png)

#### Relevant stacktraces

```python
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux send-keys -t 'None' \"echo **START**;cd /opt/jumpscale9/apps/atyourservice; python3 main.py -h 0.0.0.0 -p 5000 --log info && echo **OK** || echo **ERROR**\" ENTER"
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 j.tools.prefab.local.js9.atyourservice.start()

/opt/code/github/jumpscale/prefab9/modules/js9/PrefabAtYourService.py in start(self, log, dev)
    140             cmd += " --dev "
    141         pm = self.prefab.system.processmanager.get()
--> 142         pm.ensure('atyourservice', cmd=cmd)
    143
    144     def stop(self):

/opt/code/github/jumpscale/prefab9/modules/system/ProcessManager.py in ensure(self, name, cmd, env, path, descr, autostart, wait, expect)
    315                 if wait:
    316                     self.prefab.core.file_write(self.startupfile, 'sleep %s' % wait, append=True)
--> 317         self.prefab.system.tmux.executeInScreen("main", name, cmd, wait=wait, expect=expect)
    318
    319     def stop(self, name):
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "main.py", line 59, in init_ays
    j.clients.ssh.ssh_keys_load(key_path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClientFactory.py", line 243, in ssh_keys_load
    j.sal.process.executeInteractive(cmd)
  File "/opt/code/github/jumpscale/core9/JumpScale9/sal/process/SystemProcess.py", line 568, in executeInteractive
    raise RuntimeError("Could not execute %s" % command)
RuntimeError: Could not execute ssh-add -t 86400 /root/.ssh/ays_repos_key
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 72, in main
    sanic_app.run(debug=debug, host=host, port=port, workers=1)
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 646, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 588, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 496, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "main.py", line 59, in init_ays
    j.clients.ssh.ssh_keys_load(key_path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClientFactory.py", line 243, in ssh_keys_load
    j.sal.process.executeInteractive(cmd)
  File "/opt/code/github/jumpscale/core9/JumpScale9/sal/process/SystemProcess.py", line 568, in executeInteractive
    raise RuntimeError("Could not execute %s" % command)
RuntimeError: Could not execute ssh-add -t 86400 /root/.ssh/ays_repos_key
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
**ERROR**
root@8d8ba9c435ae:/opt/jumpscale9/apps/atyourservice# exit
logout

[main] 0:atyourservice*                                                                                                                                                                                  "8d8ba9c435ae" 09:29 28-Feb-18

/opt/code/github/jumpscale/prefab9/modules/system/PrefabTmux.py in executeInScreen(self, sessionname, screenname, cmd, wait, cwd, env, user, tmuxuser, reset, replaceArgs, resetAfter, die, expect)
    174         if die and rc > 0:
    175             # TODO: *1 does not seem to stop
--> 176             raise j.exceptions.RuntimeError(out)
    177
    178         return rc, out

RuntimeError: ERROR:  ((type:runtime.error)

In [3]: j.tools.prefab.local.js9.atyourservice.start()
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:test -e /opt/jumpscale9/apps/atyourservice/main.py
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;test -e /opt/jumpscale9/apps/atyourservice/main.py"
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux lsw
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux lsw"
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux list-panes -t "main" -F "#{pane_pid};#{window_name}" -a
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux list-panes -t \"main\" -F \"#{pane_pid};#{window_name}\" -a"
[Wed28 09:29] - PrefabCore.py       :1303:j.prefab.core                  - INFO     - RUN:pgrep -P 1876
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;pgrep -P 1876"
[Wed28 09:29] - PrefabCore.py       :1303:j.prefab.core                  - INFO     - RUN:kill -9 1876
exec:set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;kill -9 1876"
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux list-windows -F "#{window_index}:#{window_name}" -t "main"
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux list-windows -F \"#{window_index}:#{window_name}\" -t \"main\""
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux kill-window -t 'None'
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux kill-window -t 'None'"
[Wed28 09:29] - PrefabCore.py       :1303:j.prefab.core                  - INFO     - RUN:ps -A | grep atyourservice ; true
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ps -A | grep atyourservice ; true"
[Wed28 09:29] - ProcessManager.py   :333 :j.prefab.system.processmanager - INFO     - ...ok
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux list-sessions -F "#{session_name}"
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux list-sessions -F \"#{session_name}\""
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:which 'tmux'
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;which 'tmux'"
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux kill-session -t 'main'
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux kill-session -t 'main'"
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux new-session -d -s main -n atyourservice
exec:set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux new-session -d -s main -n atyourservice"
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux list-windows -F "#{window_index}:#{window_name}" -t "main"
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux list-windows -F \"#{window_index}:#{window_name}\" -t \"main\""
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux send-keys -t 'main:0' "echo **START**;cd /opt/jumpscale9/apps/atyourservice; python3 main.py -h 0.0.0.0 -p 5000 --log info && echo **OK** || echo **ERROR**" ENTER
exec:bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux send-keys -t 'main:0' \"echo **START**;cd /opt/jumpscale9/apps/atyourservice; python3 main.py -h 0.0.0.0 -p 5000 --log info && echo **OK** || echo **ERROR**\" ENTER"
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux capture-pane -pS -5000 -J
exec:set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux capture-pane -pS -5000 -J"
[Wed28 09:29] - PrefabCore.py       :1305:j.prefab.core                  - DEBUG    - RUN:tmux capture-pane -pS -5000 -J
exec:set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;tmux capture-pane -pS -5000 -J"
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "main.py", line 59, in init_ays
    j.clients.ssh.ssh_keys_load(key_path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClientFactory.py", line 243, in ssh_keys_load
    j.sal.process.executeInteractive(cmd)
  File "/opt/code/github/jumpscale/core9/JumpScale9/sal/process/SystemProcess.py", line 568, in executeInteractive
    raise RuntimeError("Could not execute %s" % command)
RuntimeError: Could not execute ssh-add -t 86400 /root/.ssh/ays_repos_key
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 72, in main
    sanic_app.run(debug=debug, host=host, port=port, workers=1)
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 646, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 588, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 496, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "main.py", line 59, in init_ays
    j.clients.ssh.ssh_keys_load(key_path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClientFactory.py", line 243, in ssh_keys_load
    j.sal.process.executeInteractive(cmd)
  File "/opt/code/github/jumpscale/core9/JumpScale9/sal/process/SystemProcess.py", line 568, in executeInteractive
    raise RuntimeError("Could not execute %s" % command)
RuntimeError: Could not execute ssh-add -t 86400 /root/.ssh/ays_repos_key
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
**ERROR**
```

**Comment by yveskerwyn** [comment]
Unable to reproduce with updated `jumpscale/ays-server` image
