### ISSUE TITLE
Multipule times the same log in run

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#65]
#### Installation information

- jumpscale version: 9.1.0

#### Detailed description
I should only be seeing one

#### Steps to reproduce

Create a service with a RuntimeError

#### Relevant stacktraces

```
In [23]: run.json()
Out[23]: 
{'epoch': 1498996332,
 'key': 'f7e16135f840146230315a1cddd3e81f',
 'state': 'error',
 'steps': [{'jobs': [{'action_name': 'install',

     'actor_name': 'fail',
     'key': '1deb3fb02749fb76387d13094ecee24a',
     'logs': [{'category': 'trace',
       'epoch': 1498996333,
       'level': 1,
       'log': 'RuntimeError: test',
       'tags': ''},
      {'category': 'errormsg',
       'epoch': 1498996333,
       'level': 40,
       'log': 'Traceback (most recent call last):\n  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/tmp/actions/fail/1b7be254a05b0ae54e61ac4546f1e7a5.py$
, line 130, in install\n    raise RuntimeError("test")\nRuntimeError: test',
       'tags': ''},
      {'category': 'trace',
       'epoch': 1498996343,
       'level': 1,
       'log': 'RuntimeError: test',
       'tags': ''},
      {'category': 'errormsg',
       'epoch': 1498996343,
       'level': 40,
       'log': 'Traceback (most recent call last):\n  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/tmp/actions/fail/1b7be254a05b0ae54e61ac4546f1e7a5.py$, line 130, in install\n    raise RuntimeError("test")\nRuntimeError: test',
       'tags': ''},
      {'category': 'trace',
       'epoch': 1498996373,
       'level': 1,
       'log': 'RuntimeError: test',
       'tags': ''},
      {'category': 'errormsg',
       'epoch': 1498996373,
       'level': 40,
       'log': 'Traceback (most recent call last):\n  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/tmp/actions/fail/1b7be254a05b0ae54e61ac4546f1e7a5.py$, line 130, in install\n    raise RuntimeError("test")\nRuntimeError: test',
       'tags': ''},
      {'category': 'trace',
       'epoch': 1498996433,
       'level': 1,
       'log': 'RuntimeError: test',
       'tags': ''},
      {'category': 'errormsg',
       'epoch': 1498996433,
       'level': 40,
       'log': 'Traceback (most recent call last):\n  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/tmp/actions/fail/1b7be254a05b0ae54e61ac4546f1e7a5.py$
, line 130, in install\n    raise RuntimeError("test")\nRuntimeError: test',
       'tags': ''},
      {'category': 'trace',
       'epoch': 1498996733,
       'level': 1,
       'log': 'RuntimeError: test',
       'tags': ''},
      {'category': 'errormsg',
       'epoch': 1498996733,
       'level': 40,
       'log': 'Traceback (most recent call last):\n  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/tmp/actions/fail/1b7be254a05b0ae54e61ac4546f1e7a5.py$
, line 130, in install\n    raise RuntimeError("test")\nRuntimeError: test',
       'tags': ''}],
     'service_key': '1b7be254a05b0ae54e61ac4546f1e7a5',
     'service_name': 'main',
     'state': 'error'}],
   'number': 1,
   'state': 'error'}]}
```

**Comment by ashraffouda** [comment]
@rkhamis  each the epoch is not the same it has like 5 mins diff and this is reasonable because we reschedule the failed runs
