### ISSUE TITLE
AYS API raml console JSON error

### ISSUE THREAD

**Issue by arahmanhamdy** [Jumpscale/ays9#66]
#### Installation information

- jumpscale version: 9.0.3
- operating system: Ubuntu 16.04

#### Detailed description
The api requests gives json load error if we use the AYS api raml console

#### Steps to reproduce
1 - ays start
2 - go to: http://<JS9_CONTAINER_IP>:5000/apidocs/index.html?raml=api.raml
3 - use any api endpoint which uses json body (i.e. /ays/template_repo)
4 - fill the body of the request (i.e {'url':'<GIT_URL>'})

#### Relevant stacktraces
2017-07-02 14:20:48 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/request.py", line 67, in json
    self.parsed_json = json_loads(self.body)
ValueError: Expected object or value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 178, in post
    return await auth(request, ays_api.addTemplateRepo(request))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 14, in auth
    return await func
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 37, in addTemplateRepo
    inputs = request.json
  File "/usr/local/lib/python3.5/dist-packages/sanic/request.py", line 71, in json
    raise InvalidUsage("Failed when parsing body as json")
sanic.exceptions.InvalidUsage: Failed when parsing body as json

**Comment by arahmanhamdy** [comment]
The issue was because of using single quotes instead of double quotes in json object
