### ISSUE TITLE
VM template to snapshot/delete snapshot/rollback to snapshot/list snapshots *

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#76]
Rollback is not ready. Rest are.
Rollback work is being done [here](https://github.com/zero-os/0-orchestrator/issues/430)

Corresponds to API: 
 - /cloudapi/machines/snapshot
 - /cloudapi/machines/rollbackSnapshot
 - /cloudapi/machines/deleteSnapshot
 - /cloudadpi/machines/listSnapshots

Docs and tests must be included

part of #64

**Comment by ahmedelsayed-93** [comment]
### scenario 
- execute take snapshot blueprint ### scenario 
- execute take snapshot blueprint 
- create the run 
- get the epoc of the snapshot
- execute delete snapshot blueprint
- create the run 

### ays log
```
Error of job: node.ovc!demo (delete_snapshot):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/6a351a90b677bb45902907ee4d98971b.py", line 602, in delete_snapshot
    machine.delete_snapshot(snapshot_epoch)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 585, in delete_snapshot
    self.client.api.cloudapi.machines.deleteSnapshot(machineId=self.id, epoch=epoch)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 44, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Param with name:epoch is missing.

```

### Note
this scenario is working fine
- create snapshot using ovc ui (not ays)
- get the epoc of the snapshot
- execute delete snapshot blueprint
- create the run 
- create the run 
- get the epoc of the snapshot
- execute delete snapshot blueprint
- create the run 

### ays log
```
Error of job: node.ovc!demo (delete_snapshot):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/6a351a90b677bb45902907ee4d98971b.py", line 602, in delete_snapshot
    machine.delete_snapshot(snapshot_epoch)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 585, in delete_snapshot
    self.client.api.cloudapi.machines.deleteSnapshot(machineId=self.id, epoch=epoch)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 44, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Param with name:epoch is missing.

```

### Note
this scenario is working fine
- create snapshot using ovc ui (not ays)
- get the epoc of the snapshot
- execute delete snapshot blueprint
- create the run

**Comment by ahmedelsayed-93** [comment]
### scenario 
- execute take snapshot blueprint
- create the run 
- get the epoc of the snapshot
- execute delete snapshot blueprint
- create the run 

### ays log
```
Error of job: node.ovc!demo (delete_snapshot):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/6a351a90b677bb45902907ee4d98971b.py", line 602, in delete_snapshot
    machine.delete_snapshot(snapshot_epoch)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 585, in delete_snapshot
    self.client.api.cloudapi.machines.deleteSnapshot(machineId=self.id, epoch=epoch)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 44, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 400 Bad Request
Param with name:epoch is missing.

```

### Note
this scenario is working fine
- create snapshot using ovc ui (not ays)
- get the epoc of the snapshot
- execute delete snapshot blueprint
- create the run

**Comment by alichaddad** [comment]
The reason for that is during the execution of the first blueprint the model data is set and the value of `snapshotEpoch` is none. when executing the second blueprint the data won't change because process change won't trigger because the value of the parameter wasn't set in the first place, so it will remain none.

**Comment by john-kheir** [comment]
Verified
