### ISSUE TITLE
VM template to start/stop/reboot/pause/reset/resume

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#77]
Corresponds to API: 
 - /cloudapi/machines/start
 - /cloudapi/machines/stop
 - /cloudapi/machines/reboot
 - /cloudapi/machines/pause
 - /cloudapi/machines/reset
 - /cloudapi/machines/resume

Docs and tests must be included

part of #64

**Comment by ahmedelsayed-93** [comment]
### Scenario 
- create vm from the ovc portal.
- add at least one port forward rule.
- stop the vm from the ovc portal.
- execute start vm blueprint and create the run 

#### blueprint 
```yaml
g8client__env:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: '<username>'
    password: '<password>'
    account: '<account>'

vdc__test_vm_ops:
    location: 'du-conv-2'

node.ovc__test-demo:

actions:
  - action: start
    actor: node.ovc
    service: test-demo
``` 

### steps 

![image](https://user-images.githubusercontent.com/24386820/29003850-bcfe7d86-7abe-11e7-9f05-adf65a218d1a.png)

### ays error
```
Error of job: node.ovc!test-demo (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 591, in create_portforwarding
    publicPort=realpublicport
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 43, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 409 Conflict
Forward to 192.168.28.166 with port 2200 already exists

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/a746265dabb9fca13e9f93cc8e7e2edf.py", line 281, in install
    public, local = machine.create_portforwarding(publicport=public_port, localport=local_port, protocol='tcp')
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Client.py", line 602, in create_portforwarding
    raise j.exceptions.RuntimeError("Port forward already exists. Please specify another port forwarding")
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Port forward already exists. Please specify another port forwarding ((type:runtime.error)

```

### software version 
master : 9621eb0
