### ISSUE TITLE
VM template to clone machine *

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#81]
Corresponds to API: 
 - /cloudapi/machines/clone

Docs and tests must be included

part of #64

**Comment by ahmedelsayed-93** [comment]
### run details
```
Current state of the run:

RUN:2014c0545df1576f575cf1cf26026473 (error)
step:1 (ok)
- os.ssh.ubuntu             demo                           | stop            (ok)
- sshkey                    auto_0                         | install         (ok)
- g8client                  env                            | install         (ok)
- vdcfarm                   auto_3                         | install         (ok)
step:2 (error)
- account                   test_js913                     | install         (ok)
- node.ovc                  demo                           | stop            (error)
step:3 (new)
- vdc                       test_clone                     | install         (new)
step:4 (new)
- node.ovc                  demo                           | install         (new)
step:5 (new)
- node.ovc                  demo                           | clone           (new)

```
### ays log
```
Error of job: node.ovc!demo (stop):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/6de9bcbe930adf34978de123b897ca57.py", line 470, in stop
    _check_ssh_authorization(job.service, machine)
  File "/tmp/actions/node.ovc/6de9bcbe930adf34978de123b897ca57.py", line 734, in _check_ssh_authorization
    prefab = _ssh_authorize(service, vm_info)
  File "/tmp/actions/node.ovc/6de9bcbe930adf34978de123b897ca57.py", line 445, in _ssh_authorize
    executor.prefab.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabSSH.py", line 133, in authorize
    d = self.prefab.user.check(user, need_passwd=False)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabUser.py", line 82, in check
    _, d, _ = self.prefab.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1108, in run
    cmd = self.replace(cmd)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 275, in replace
    args2 = self.getArgsDict()
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 305, in getArgsDict
    for key, var in self.dir_paths.items():
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 215, in dir_paths
    return self.executor.dir_paths
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 336, in dir_paths
    if self.exists(self.state.configPath):
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 35, in state
    self._state = State(self)
  File "/opt/code/github/jumpscale/core9/JumpScale9/core/State.py", line 16, in __init__
    if self.executor.exists("/etc/") and self.executor.platformtype.isMac == False:
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 130, in exists
    return self.cache.get("exists:%s"%path, check)
  File "/opt/code/github/jumpscale/core9/JumpScale9/data/cache/Cache.py", line 115, in get
    val = method(**kwargs)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 125, in check
    rc,_,_=self.execute('test -e %s'%path,die=False,showout=False)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorSSH.py", line 237, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 214, in execute
    ch = self.transport.open_session()
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 127, in transport
    raise j.exceptions.RuntimeError("Could not connect to %s:%s" % (self.addr, self.port))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Could not connect to :0 ((type:runtime.error)


******************************************************************************************

[Sun17 11:28] - RunScheduler.py     :161 :j.ays.runscheduler             - INFO     - reschedule run 2014c0545df1576f575cf1cf26026473 in 30sec
```

### software version
master : 120b4d72

**Comment by john-kheir** [comment]
Verified
